Feature/mutations
Bridgeconn/vachan-api pull request #179
Opened 2021-07-07 11:07 UTC by sijumoncy

This branch have the Mutations created for ADD and UPDATE features of Languages.

2021-07-07 11:53 UTC, kavitharaju requested changes
Adding few points that struck me at first glance. Shall run and test locally and respond. You can take a look at these in the mean while.

Are new files `app/tkn_offset[0]` and `edited parts.txt` required?

Did you use pylint? It shows warnings(see the bottom of PR page), because of trailing spaces and multiple new lines at the end of file.

2021-07-07 11:53 UTC, kavitharaju commented on app/crud/utils.py
> +    print("--STDOUT----=",stdout)
These prints added while debugging or development could be removed

2021-07-07 11:53 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +        print("==============================================")
We could remove print statments like this to keep code base cleaner

2021-07-08 08:09 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +        return AddLanguage(language = language)
Can we also return a message stating if the operation was successful or like in REST's response

2021-07-08 08:09 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    metaData = graphene.JSONString()
May be a description would be good here, stating we expect a dict like value as it is not very self explanatory

2021-07-08 08:09 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +        language_Addargs = InputAddLang(required=True)
I see we are expecting an input object here instead of individual parameters like you mentioned in our discussion. Is there a reason for doing it this way?

2021-07-09 04:36 UTC, kavitharaju requested changes

2021-07-09 04:36 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    metaData = graphene.JSONString(description="Expecting a dictionary Type")
I think we need to keep only language Id required here. That is how it is in REST right?
![image](https://user-images.githubusercontent.com/18255929/125022900-5412c100-e09b-11eb-8183-11e6ec93f138.png)

2021-07-09 04:36 UTC, kavitharaju commented on app/graphql_api/types.py
> +    language_id = graphene.Int()
We use camel casing as much as possible in the output, to stick to the JS practices. As our clients are mostl in JS

2021-07-09 04:36 UTC, kavitharaju commented on app/test/test_graphql_languages.py
> +    assert isinstance(executed["data"]["languages"], list)
we also need to test the queried fields, like language, code etc, are in the result.

2021-07-09 04:36 UTC, kavitharaju commented on app/test/test_graphql_languages.py
> +    assert executed == {"data": {"languages": [{"language": "Afar"}]}}
This is a risky test. We cannot always guarantee this particluar language would the first returned. It will depend on the order languages were inserted in DB. Better query for this  language specifying language name or code

2021-07-09 05:02 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    language_type = graphene.Field(types.Language)
Its would be better to name it differently that just `Output`. There is going to be more output objects for each of the API group. So follow a naming pattern that can be adopted throughout

2021-07-09 05:08 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    metaData = graphene.JSONString(description="Expecting a dictionary Type")
Is scriptDirection a required field in REST?

2021-07-09 06:34 UTC, kavitharaju commented on app/'
> +Unable to initialize device PRN
If this new file used for anything?

2021-07-09 06:40 UTC, kavitharaju commented on app/graphql_api/types.py
> +    language_id = graphene.Int()
I see you changed it to languageId. Is it working as expected now?

2021-07-09 06:44 UTC, sijumoncy commented on app/'
> +Unable to initialize device PRN
I think its automatically created and none of these files have any connection with the feature/mutations

2021-07-09 09:18 UTC, kavitharaju commented on app/'
> +Unable to initialize device PRN
Oh, is it? Okay then. I am going to approve and merge this PR. We can check why these files are being created and also add more tests for these mutations as the next task

2021-07-09 09:19 UTC, merged