Feature/mutations
Bridgeconn/vachan-api pull request #205
Opened 2021-07-21 10:58 UTC by sijumoncy

@kavitharaju @samuelanthrayose 
#195 #196 

PR for mutation and test of GraphQL bible-api and commentaries

2021-07-22 04:45 UTC, kavitharaju requested changes

2021-07-22 04:45 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    books = graphene.List(graphene.JSONString,required=True,\
Need to specify the expected inner contents as USFM and/or JSON. I suggest you use a separate InputObject like the `BibleBookUpload` used in REST

2021-07-22 04:45 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    JSON = graphene.JSONString(description="JSON Data")
Not any JSON would be accespted here. Only JSON structure obtained from USFM-Grammar or one like that would be accepted. So its good to specify that too in description

2021-07-22 04:45 UTC, kavitharaju commented on app/test/test_gql_commentaries.py
> +    variable = {
Are we running a common set of sets for all GET requests(queries) to check for the correct functioning of skip, limit etc as in tests for REST?

2021-07-22 07:38 UTC, kavitharaju requested changes

2021-07-22 07:38 UTC, kavitharaju commented on app/graphql_api/mutations.py
> +    JSON = graphene.JSONString()
The same `description="Provide JSON structure obtained  from USFM-Grammar or one like that"` can be given here as well

2021-07-22 07:38 UTC, kavitharaju commented on app/test/__init__.py
> +def check_limit_gql(query,limit,api_name):
What I would suggest here is define multiple checks with different values for skip and limit in these functions itself. See how multiple cases are tested in corresponding check functions of REST. Then you will not have to multiple write long queries and call this function multiple time for each test file. Construct it such that it is called only once and pass in a minimal query which is then appended with skip and limit parameters here. That would save us a lot of code.

Also these test are to be done for all queries, not just languages and commentaries. Add them in all tests you have written before

2021-07-22 07:38 UTC, kavitharaju commented on app/test/test_gql_bibles.py
> +      {
I see you are asking for all fields in all get queries. Its good to add them in one query, later on you can just query for minimal fileds to make sure the function is working as expected. I think that would save lot of line-of-code in these test files and make it more readable

2021-07-24 04:53 UTC, kavitharaju commented on app/test/__init__.py
> +    query3 = query.replace("arg_text","skip:50000,limit:10")
Having a place holder and replacing would work too. 
But can't we pass it as variables?

2021-07-24 05:00 UTC, sijumoncy commented on app/test/__init__.py
> +    query3 = query.replace("arg_text","skip:50000,limit:10")
means?
query = """
  getsomething(sourcename:"something",variable){
        data
}
"""

like this ..?

2021-07-26 05:46 UTC, kavitharaju commented on app/test/__init__.py
> +    query3 = query.replace("arg_text","skip:50000,limit:10")
I meant using the variables as allowed by GQL format instead of hard-coding the skip and limit values.
```
query = """
        query something($skip:int, $limit:int){
        something(skip:$skip){
           ...
        }
        }
"""
```
and passing 
```
variables = {
     "$skip": 0,
     "$limit":0
}
```
to ` gql_request(query=query, operation="query", variables=variables)`

2021-07-26 07:12 UTC, sijumoncy commented on app/test/__init__.py
> +    query3 = query.replace("arg_text","skip:50000,limit:10")
i will look into it

2021-07-26 13:48 UTC, kavitharaju approved these changes

2021-07-26 13:48 UTC, merged