Kratos auth restapi
Bridgeconn/vachan-api pull request #232
Opened 2021-09-02 11:05 UTC by sijumoncy

Primary implementation of Authentication of rest Api based on Ory Kratos. Email verification of registration is currently not added in this PR
#230

2021-09-03 09:15 UTC, kavitharaju requested changes
This is a lot of code to review. 
I haven't reviewed tests or tested locally yet. 
I have made sooo many comments already. Lets get through them first.

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    password:str
passwords shouldn't be sent as plain text. There would be data type used for passwords. Use it even if we are changing this to query params

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    password:str
dont use str for password here also

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    lastname:str
This field can be optional, I think

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    appname:str
Define an enum for valid app names and use that as the type instead on any str. This filed can also be optional

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    roles:list
We can have an enum for valid roles names as well. Define these enums in one place(either here or in the authentication.py file) and import and use the same every where instead of using strings

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    Permisions:list
specify what kind of list this is. I think we can specify types as `[str]` , `[int]` etc. If these permissions are user roles use the same enum as before

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    details:str
If these `details` field is like the "message" we use in other responses, it is better to rename them to "message" to have uniformity.

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    details:str
I think we already have a schema defined for error.

2021-09-03 09:15 UTC, kavitharaju commented on app/schema_auth.py
> +    role_list:list
define enum and use `[enum_name]` as type

2021-09-03 09:28 UTC, sijumoncy commented on app/authentication.py
> +     "http://127.0.0.1:4433/sessions/whoami")
For public and admin the ports are different and base is same and also the 3 rd one can be created from the admin iits self

2021-09-03 09:36 UTC, sijumoncy commented on app/schema_auth.py
> +    lastname:str
I think all field in the kratos schema should provide

2021-09-03 09:38 UTC, kavitharaju commented on app/authentication.py
> +     "http://127.0.0.1:4433/sessions/whoami")
okay, then keep as two different values

2021-09-08 08:41 UTC, kavitharaju requested changes
Suggestions
1. start env variable names with VACHAN_
2. In the error response, the "error" should say "Authentication Error" intead of "Http Error". Define a new custom exception for this if required. In "details" its better to give what ever error message you get from Kratos intead of giving our own texts like "Invalid Credential".
3. In the login api, use "user_email" instead of "username" as we ask for first name and last name also in registaration, this can be confusing
4. Please change the order of including router for Auth_apis in main.py, so that Authentication APIs willcome at the top of API docs and not at the end
5. Add new folder named Kratos_config. Add the config files needed there and also write an instructions.md file with the steps and commands we need to start the Kratos instance locally. This is for temporory purpose. Kratos will be setup separately. But noting down our methods now can help us work smoothly now and later to set up the central instance.
6. Should do logging in auth APIs(routers) also, like we have for other APIs

7. I faced following problems when testing locally
	1. Even though app started successfully(creating super user), was not able to login with super user credentials
	2. When I tried to register a new user with not safe password, the actual Kratos response was "'The password can not be used because the password has been found in data breaches...", but the API just gave a null with 201 status. I think the issue is at the check `if "messages" in reg_response["ui"]`. In this case `reg_response["ui"]` is an array.
	3. Throws Keyerror: 'userrole' at line 170, authentication.py, when I used superuser email agian for registartion

2021-09-13 04:05 UTC, sijumoncy commented
#234 
Added ENV variable TEST_MODE in github action to "handle super user creation" cause error because of the absence of kratos instance

2021-09-16 13:55 UTC, kavitharaju approved these changes
The some of the auth tests are still failing for me.

One reason for test failure is that the users created once are persisting in the Kratos DB and whe run again, it gives "Already Exists".

But merging this PR as other features are working. Tests can be fixed as another issue

2021-09-16 13:55 UTC, merged