POST API to add new SWs for a language
Bridgeconn/vachan-api pull request #291
Opened 2021-11-23 10:18 UTC by anjalyv

- v2/lookup/stopwords/<lang_code>
-  Accept a list of stopwords like,
[
{
    "stopWord": "क्योंकि",
    "metaData": {
      "type": "preposition"
    }
  },
  {
   "stopWord": "ने",
}
]

- For each word :
    If present in db and is predefined or added by a user, leave it as such
    If already present, and is auto generated update its confidence =  1, updated_user, active =True
    If not present add them to DB with confidence score =1 , active =True

2021-11-23 12:55 UTC, kavitharaju requested changes

2021-11-23 12:55 UTC, kavitharaju commented on app/crud/nlp_sw_crud.py
> +                        word_dic.stopWord, db_models.StopWords.languageId == language_id).first()
why do we need to execute a new query here? wouldn't the `result` object have this row and values?

2021-11-23 12:55 UTC, kavitharaju commented on app/routers/translation_apis.py
> +    stopwords_list:List[schemas_nlp.StopWordsAdd]=Body(...),
May be we can just have `stopwords_list:List[str]=Body(..., example=....)`

2021-11-23 12:55 UTC, kavitharaju commented on app/schemas_nlp.py
> +    metaData: dict = Field(None, example={
As per our last discussion we had decided to not include metdata field in this POST. It will create confusion as to which metadata to be persisted in the scenario where we have an autogenarated version of same SW, whose confidence value get updated by this call

2021-11-23 12:55 UTC, kavitharaju commented on app/schemas_nlp.py
> +    message: str = Field(..., example="Stopwords saved successfully")
The example could be changed as per the changed message where we also give the number

2021-11-23 12:55 UTC, kavitharaju commented on app/test/test_stop_words_generation.py
> +    response = client.post(UNIT_URL+'/hi?',headers=headers, json=add_obj)
Are we covering enough cases where added stopwords are present/not present, have different confidences, different active values etc?

also I would suggest we use a different dummy language name and not Hindi for tests as this may cause problem with the actual hindi data we have in a deployed instance

2021-11-23 14:19 UTC, anjalyv commented on app/crud/nlp_sw_crud.py
> +                        word_dic.stopWord, db_models.StopWords.languageId == language_id).first()
No `result` object does not return rows.

2021-11-24 06:18 UTC, kavitharaju reviewed
I suggest we add more tests to cover all different cases of how SW adding can happen.
For example we could follow some pattern like this,
1. Add some tests for predefned case
    choose lang: hi

    1. add a known sw and make sure it is not getting updated
     2. add a content word as sw(to make sure it will get updated)
2. test for user-defined case
    1. choose an unknown langauge and upload sws in it
    2. Then try adding an already added sw again
    3. Add new SW to the same language
3. test for auto-genarated case
      this cannot be done until you finish the other API too, but mmake sure all cases are covreed then

2021-11-24 12:31 UTC, kavitharaju approved these changes

2021-11-24 12:32 UTC, merged