Version 2
Bridgeconn/vachan-api pull request #341
Opened 2022-02-11 11:18 UTC by sijumoncy

The Bible Project Changes #335

2022-02-12 04:51 UTC, kavitharaju requested changes

2022-02-12 04:51 UTC, kavitharaju commented on app/routers/content_apis.py
> +    search_word: str = Query(None, example="Sri Lanka"),
We could use a different example for search word that makes more sense in the context of Bible Videos.

2022-02-12 04:51 UTC, kavitharaju commented on app/schema/schemas.py
> +#pylint: disable=too-many-lines
If it is the matter of just one or two lines, we can remove some empty lines or bring up a bracket to adjust that.
If it is more than that consider adding a new schema file. Need not disable it

2022-02-12 04:51 UTC, kavitharaju commented on app/schema/schemas.py
> +    references: List[dict]
Can't we specify a proper class here, instead of dict?

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +def bcv_to_ref(bcvref,db_):
Please check if there is similar functonality implemented elsewhere in the code base and make sure we are not redefining existing logic for ref_to_bcv and bcv_to_ref

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +                CAST(ele AS TEXT) LIKE '{code+chapter}%')'''
Do we need to cast it to text? Wouldn't performing integer comparisons be more efficient?
Somethig like bbccc000 <= ele < (bbccc000+1000)

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +                WHERE CAST(ele AS TEXT) LIKE '{code}%')'''
Here also, consider performing integer operations instead of casting to text.
bb000000 <= ele <(bb000000+1000000)

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            query = query.filter(model_cls.refIds.any(int(bcv)))
This is a usecase to consider...
When we query with a specific verse, do you think we need to return video tagged as related to that whole chapter and whole book too?

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            elif not buk.verseEnd is None:
do we need "elif" here? wouldn't "else" be enough?

2022-02-12 04:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +                    buk.verseStart = 0 if buk.verseStart is None else buk.verseStart
This logic seems to be replicated in upload and update. And pylint does make complaints about too many locals and branches. may be we can move this logic out as a function and call it from both places. Consider if that is possible

2022-02-12 05:05 UTC, sijumoncy commented on app/schema/schemas.py
> +#pylint: disable=too-many-lines
it have 50 to 55 line more , if my thought correct

2022-02-12 05:07 UTC, kavitharaju commented on app/schema/schemas.py
> +#pylint: disable=too-many-lines
Then see if you can split the file logically

2022-02-16 03:48 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            book_chapter = int(str(book.bookId)+str(chapter)+"000")
The more efficient way to get the book chapter number from book number and chapter number is this
book_chapter = book.bookId * 1000,000 + chapter*1000

2022-02-16 03:51 UTC, kavitharaju requested changes

2022-02-16 03:51 UTC, kavitharaju commented on app/crud/contents_crud.py
> +                WHERE ele >= {code} AND ele < {code+1000000})'''
I see you have used <= > here and BETWEEN above. Which is better? Use the better one

2022-02-16 10:10 UTC, kavitharaju approved these changes

2022-02-16 10:10 UTC, merged