Feature/refactor auth
Bridgeconn/vachan-api pull request #454
Opened 2022-11-17 09:19 UTC by sijumoncy

**Basic Refactor of Auth module **

- [x]  Authentication Change to DB Based from File Based
- [x] update Seed Db scripts for default values and tables
- [x] Moving permission map, access rules and corresponding data to DB
- [x] Permission map, access rules and other required, default values added in csv to upload through seed script 
- [x] Implemented Functions to load required data from DB
- [x] Refactored authentication module for the changes
- [x] Necessary changes in test config and test cases
- [x] Endpoints for App ( Register, Generate Key, Remove key, Delete App, Edit )
- [x] Removed Header based app identification to key through query params. Query params for key added for all endpoints
- [x] kratos and instance and schema created for handling app (only working on local, need to fix other ymls) ( using V10.1 )

Test is not running because of kratos version and issue in config yml (Working fine in local )

2022-11-18 06:05 UTC, kavitharaju reviewed
Reviewed only the files with core changes. But lets continue the discussions on this PR.

2022-11-18 06:05 UTC, kavitharaju commented on app/auth/auth_app.py
> +DEFAULT_APPS = [
Is this the place we keep this data? Shouldn't it be at seed DB?
Only password fields need to be read from ENV and filled in, in code, rest can be from seed DB, right?

2022-11-18 06:05 UTC, kavitharaju commented on app/auth/auth_app.py
> +    {
We dont need a separate App for API user. If no app token is provided we can assume its API user.

2022-11-18 06:05 UTC, kavitharaju commented on app/db_models.py
> +    createdUser = Column('created_user', String)
It may be good to have role description and also a field associated App, which can be null also

2022-11-18 06:05 UTC, kavitharaju commented on app/routers/auth_api.py
> +# @get_auth_access_check_decorator
why is the decorator commented off?

2022-11-18 06:05 UTC, kavitharaju commented on app/routers/auth_api.py
> +    return login_kratos(app_email,password,from_app=True)
If we use the same function as for users, then where do we tell that its supposed to use the other Kratos?

2022-11-18 06:05 UTC, kavitharaju commented on app/routers/auth_api.py
> +def delete_key(app_key: types.SecretStr,
Auth decorator is missing

2022-11-18 06:05 UTC, kavitharaju commented on app/routers/content_apis.py
> +    user_details =Depends(get_user_or_none),db_: Session = Depends(get_db)):
Wouldn't we need a dependency, app_details = Depends(get_app_or_none) ? Of it is it handled inside the auth decorator>

2022-11-18 06:47 UTC, sijumoncy commented on app/auth/auth_app.py
> +DEFAULT_APPS = [
The basic data of default apps keep in one of the code base file is because we are using this data in other places ( like test conf) . we can set the password field as ENV. The seed Db is only using the name of the default app not other details.

2022-11-18 06:51 UTC, sijumoncy commented on app/auth/auth_app.py
> +    {
yes the code base is working in that way , no token is provided will be treated as request from API. This is currently only used in test , we can remove this app from the default app list if needed

2022-11-18 06:55 UTC, sijumoncy commented on app/db_models.py
> +    createdUser = Column('created_user', String)
we already have a relation with app and role . right ? app with default role . do we need the relation 2 way . 
If so does that makes complex database operations
register app :
 role add to table first for a new app
app add to app table and  that role add to default role in app table

2022-11-18 06:56 UTC, sijumoncy commented on app/routers/auth_api.py
> +# @get_auth_access_check_decorator
Forgot to remove comment , commented on development

2022-11-18 07:02 UTC, sijumoncy commented on app/routers/content_apis.py
> +    user_details =Depends(get_user_or_none),db_: Session = Depends(get_db)):
user details dependency is for the user who is requesting ?

2022-11-18 08:28 UTC, sijumoncy commented on app/db_models.py
> +    createdUser = Column('created_user', String)
WE can enforce to have role connected to an app name when add a new ROLE in db via role add API

2022-11-21 13:32 UTC, kavitharaju requested changes

2022-11-21 13:32 UTC, kavitharaju commented on app/auth/auth_app.py
> +    {
If you are planning to do this in separate PR make sure you create an issue for this or a task in a main issue

2022-11-21 13:32 UTC, kavitharaju commented on app/schema/schema_auth.py
> +#     BCSDEV = 'BcsDeveloper'
We could remove the commented portions. Coming back and cleaning up may not happen always. If we need to reference them we will be keeping the version-2 branch seperate, right? So no risk I guess.

2022-11-21 13:32 UTC, kavitharaju commented on app/schema/schema_auth.py
> +    roles:list[str]
When you add remaining tasks to be done, please add one to ensure we write tests for raising  database errors for invalid roles, apps, permissions etc.

2022-11-21 13:32 UTC, kavitharaju commented on app/schema/schema_auth.py
> +    password:types.SecretStr
we are expecting Vachan Admin to store these passwords manually right? And also tokens also, right?

2022-11-21 13:32 UTC, kavitharaju commented on app/routers/auth_api.py
> +    * Loging out will end the expiry of a token even if the time period not expired.'''
If we are to use this API for revoking an APP token, what would be the expected usage?
- user_token of VA or SA in the auth header
- app_key in the query param
Is this right?
What happens then? Isn't the user gonna get logged out instead of the app? Do we have another API to expire APP token?

2022-11-21 13:32 UTC, kavitharaju commented on db/csvs/auth_resource_types.csv
> +resource_type_name,resource_type_description
I think the file could be named `api_resource_types.csv`

2022-11-21 13:32 UTC, kavitharaju commented on docker/Kratos_config/email-password/kratos-app.yml
> +    base_url: http://kratos:4443/
This and the below one are the container names we discussed about changing.

2022-11-21 13:32 UTC, kavitharaju commented on docker/Kratos_config_App/database.yml
> +      - DSN=${VACHAN_APP_AUTH_DATABASE:-postgres://kratos:secret@postgresd:5434/kratos?sslmode=disable&max_conns=20&max_idle_conns=4}
I think it would be worth taking a look at the port numbers of the Kratos postgres DBs. Here I see 5434. Some where else I saw 5435. Better stick to one on all places, quickstart, database and test-dependencies to avoid confusion

2022-11-21 13:32 UTC, kavitharaju commented on docker/Kratos_config_App/email-password/kratos.yml
> +version: v0.4.6-alpha.1
Is this version correct?

2022-11-21 13:32 UTC, kavitharaju commented on docker/Kratos_config_App/database.yml
> +version: "3.7"
Why do we have both folders `docker/Kratos_config` and `docker/Kratos_config_App` with similar files repeated? Can't we just keep one?

2022-11-21 13:32 UTC, kavitharaju commented on docker/run-tests.yml
> +      - VACHAN_KRATOS_APP_ADMIN_URL=http://kratos:4444/
Are both set of URLs connecting to same "kratos" container here? Should the app ones be different?

2022-11-22 04:14 UTC, sijumoncy commented on app/auth/auth_app.py
> +    {
https://github.com/Bridgeconn/vachan-api/issues/411 - added it as a task

2022-11-22 04:16 UTC, sijumoncy commented on app/schema/schema_auth.py
> +#     BCSDEV = 'BcsDeveloper'
ok, will remove these

2022-11-22 04:18 UTC, sijumoncy commented on app/schema/schema_auth.py
> +    roles:list[str]
We are testing the role is the global var of roles always and raise error . Will add this test in coming PR

2022-11-22 04:22 UTC, sijumoncy commented on app/schema/schema_auth.py
> +    password:types.SecretStr
this is the registration input schema for Apps can be accessed from VA app for registering app , need all these fields to create an app in kratos ?

2022-11-22 04:31 UTC, sijumoncy commented on app/routers/auth_api.py
> +    * Loging out will end the expiry of a token even if the time period not expired.'''
- This end point to revert user token. and if we pass app key in the header as like a user token , I believe will raise an error for unexpected token type .

- App key in the query params is like all other apis to pass the app token from which request is coming.
- The App key revert have another endpoint currently restricted to acces only from VA app and VA, SA can perform the revert operation as per the MAP and Rules

2022-11-22 04:31 UTC, sijumoncy commented on docker/Kratos_config/email-password/kratos-app.yml
> +    base_url: http://kratos:4443/
yes , I will change those, check and Inform

2022-11-22 04:32 UTC, sijumoncy commented on docker/Kratos_config_App/database.yml
> +      - DSN=${VACHAN_APP_AUTH_DATABASE:-postgres://kratos:secret@postgresd:5434/kratos?sslmode=disable&max_conns=20&max_idle_conns=4}
35 is in the local quickstart.yml.

2022-11-22 04:32 UTC, sijumoncy commented on docker/Kratos_config_App/email-password/kratos.yml
> +version: v0.4.6-alpha.1
this need to be changed to latest 10.1 ,

2022-11-22 04:34 UTC, sijumoncy commented on docker/Kratos_config_App/database.yml
> +version: "3.7"
Kratos_config App folder is the one method that i tried earlier for running seperate instance of kratos , that we discussed , kept this for a reference only , will remove once the current setup start working smooth

2022-11-22 04:35 UTC, sijumoncy commented on docker/run-tests.yml
> +      - VACHAN_KRATOS_APP_ADMIN_URL=http://kratos:4444/
https://github.com/Bridgeconn/vachan-api/issues/411 yes will change it to kratos-app. right ?

2022-11-22 04:59 UTC, kavitharaju commented on docker/run-tests.yml
> +      - VACHAN_KRATOS_APP_ADMIN_URL=http://kratos:4444/
yes.

2022-11-28 13:02 UTC, sijumoncy commented
- [x] Removed API user from default apps ( added only for tests )
- [x] GQL test disable using pylint command in run test yml
- [x] role table updated with app and description column
- [x] refactored app , user methods
- [x] yml files updated
- [x] filter apps enum removed
- [x] bugs and issue fixed in PR comments

2022-11-29 05:46 UTC, kavitharaju approved these changes
Lets proceed with this as we have our tests working now.
Once all APIs are in place we will be able to test them better with automated tests as well as a round of manual testing

2022-11-29 05:49 UTC, merged