Feature/delete
Bridgeconn/vachan-api pull request #455
Opened 2022-11-21 16:48 UTC by shimilgithub

2022-11-22 05:27 UTC, sijumoncy commented on app/auth/access_rules.json
> +        "create": ["registeredUser","SuperAdmin"],
SuperAdmin not needed in "create" beacuse of superAdmin is comes in registered user

2022-11-22 05:31 UTC, sijumoncy commented on app/db_models.py
> +    createdUser = Column('created_user', String)
is this created user field is for the deleted resource created user? If so this need to be come inside the json . right ?

2022-11-22 05:35 UTC, sijumoncy commented on app/routers/content_apis.py
> +            "data": data,"createdUser": user_details['user_id']}
why you are passing an extra key created user in the create contents api response . is this same data available inside the data get from the crud function

2022-11-22 05:35 UTC, kavitharaju requested changes

2022-11-22 05:35 UTC, kavitharaju commented on app/db_models.py
>      deletedUser = Column('deleted_user', String)
Here deletedUser and createdUser looks like having the same meaning and purpose. Need not keep both columns, it will only confuse us later. 
In the DB table you can call it `deleted_user`. Within code you may need to use the name "createdUser" if that is required by the auth module. If so, I suggest you map it like this
```createdUser = Column('deleted_user', String)```

2022-11-22 05:35 UTC, kavitharaju commented on app/db_models.py
>      deletedTime = Column('deleted_time', DateTime, onupdate=func.now())
Shouldn't this be `oninsert` (or whichever attribute is provided by SQLAlchemy with that meaning)? We dont want the deleted time to be altered later upon some other changes, even though there is no chances for that via API. Lets not take the risk.

2022-11-22 05:35 UTC, kavitharaju commented on app/routers/content_apis.py
> +            "data": data,"createdUser": user_details['user_id']}
Is there a need to return `user_id` in response object? I dont think we follow that anywhere else in our APIs

2022-11-22 05:35 UTC, kavitharaju commented on app/routers/content_apis.py
> +            "data": delcont,"deletedUserData": user_details['user_id']}
Here also, is there a reason why you have added user_id in response?

2022-11-22 05:35 UTC, kavitharaju commented on app/routers/content_apis.py
> +    data = json.loads(data)
Could you please explain what you are doing here? 
The `re.sub()` part. Is this how you clean off the sqlAlchemy related items from the json? If so, is this safe to assume that it will always be the first three things that you would want to remove? 
And help me understand what jsonpickle library does here. Wont handling the object as dict and letting the db_model object handle the conversion to postgres's jsonb type be a safer and more standard approach?

2022-11-22 05:43 UTC, sijumoncy commented on app/routers/content_apis.py
> +            "data": data,"createdUser": user_details['user_id']}
right. the user_id is same as created or updated user , which will be part of the CRUD response

2022-11-22 05:52 UTC, kavitharaju commented on app/routers/content_apis.py
> +    data = json.loads(data)
This regex look very unsafe to me. Usually regex matches the longest possible string. So, if "}}}" occurs further down the road in the string, we will loose data.

2022-11-22 05:53 UTC, sijumoncy commented on app/test/test_content_types.py
> +    response = client.delete(UNIT_URL, headers=headers, json=data)
use can use a loop if needed instead of all duplicate steps of test for permission denied

2022-11-22 06:02 UTC, sijumoncy commented on app/test/test_content_types.py
> +def test_delete_seed_data():
I am not sure about we need a test for seed db content can not delete.

-  I did not understand the test case , this test case always raise the exception and does that make the test fails ?
and also the delete is called as Noauth will never perform delete operation . right ?

2022-11-22 06:08 UTC, sijumoncy commented on app/test/test_content_types.py
> +def test_delete_seed_data():
you can add a test case for , if the requested content is not available in db with auth

2022-11-22 06:11 UTC, sijumoncy commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
why we are calling another test , if we do so the data will not be available after the called test ?

2022-11-22 06:12 UTC, sijumoncy commented on app/test/test_content_types.py
> +    data = {"itemId": deleteditem_id}
how to ensure that the deleted content is restored. write a get api call for the deleted content to the original table. Its better to check the original table for the content not present after perform delete operation

2022-11-22 06:17 UTC, sijumoncy commented on app/test/test_content_types.py
> +    f"Deleted Item with identity {deleteditem_id} restored successfully"
I have doubt on this restore happened correctly ? plz ensure the test runs as expected logic

2022-11-22 06:20 UTC, sijumoncy commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
@kavitharaju does this work as expected ? calling a test as a function may work . Normally the dB role back happen after completing a test. 
does this treat as a test or a normal function call ?

2022-11-22 06:22 UTC, sijumoncy commented on app/test/test_content_types.py
> +    f"Deleted Item with identity {deleteditem_id} restored successfully"
do we have a json  or something as response of the restored content to check the response is same as expected ?

2022-11-22 06:24 UTC, sijumoncy commented on app/test/test_content_types.py
> +    f"Deleted Item with identity {deleteditem_id} restored successfully"
add a test case for a non existing content restore, or try restore again the same content after 1 successful restore

2022-11-22 06:26 UTC, sijumoncy commented on app/test/test_languages.py
> +    print("edited with created user")
remove this if not necessary

2022-11-22 06:30 UTC, sijumoncy commented on app/test/test_languages.py
> +    assert response.json()['error'] == 'Authentication Error'
can use a loop inf needed as same as commented in contents type tests

2022-11-22 06:31 UTC, sijumoncy commented on app/test/test_languages.py
> +    assert response.json()['message'] == \
check for the response object too

2022-11-22 06:32 UTC, sijumoncy commented on app/test/test_languages.py
> +    assert response.json()['message'] == \
and ensure at least in one test the targeted item is deleted from the original table by a get call

2022-11-22 06:33 UTC, sijumoncy commented on app/test/test_languages.py
> +def test_delete_seed_data():
@kavitharaju Do we need a test like this ?

2022-11-22 06:34 UTC, sijumoncy commented on app/test/test_languages.py
> +def test_delete_seed_data():
I feel it like a function not as a test

2022-11-22 06:36 UTC, sijumoncy commented on app/test/test_languages.py
> +    #Restore language with AgAdmin
add a test case with resource created user if needed

2022-11-22 06:39 UTC, sijumoncy commented on app/test/test_languages.py
> +def test_restore_incorrectdatatype():
input data in json type . common post operation inputs data will be in json format. can we make this more specific to our api, like key misssing in the json/ wrong key or invalid values etc.

2022-11-22 09:43 UTC, shimilgithub commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
responses of these inside called functions are returned.Its coming when checked with print statements.

2022-11-23 05:34 UTC, shimilgithub commented on app/routers/content_apis.py
> +    data = json.loads(data)
JSONPickle is used to serialize python object to json form. This package is used since I am unable to  serialize it with other methods.
Structure of return item is like this - "SQLAlchemy related info }}}, db model values". '}}}' is not coming anywhere else when i tried with different db_models.So data is cleaned and removed sqlalchemy informations using re.sub()

2022-11-23 09:11 UTC, kavitharaju commented on app/routers/content_apis.py
> +    data = json.loads(data)
I still think this is unsafe to use that regex, because we dont know what would be the data we would encounter later.

And my second question was, what is the need for serialization? Can't you work with dictionary after `to_dict` conversion of SQLAlchemy object. Then remove the unwanted values by specifying their names explicitly.

2022-11-24 04:15 UTC, kavitharaju commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
Good point. 
The response might come, but I do not know if the changes will persist in the DB.
The calling testcase will have a transaction of itsown, but the inner one will create a new transaction and it will be rolled back at the return from inner function. This is what I assume will happen. So the changes happended in the inner function will not be available for the outer function!

2022-11-24 04:26 UTC, kavitharaju commented on app/test/test_languages.py
> +def test_delete_seed_data():
I suggested we do this test. But the way it is written doesn't make an effective test case. 
1. No auth header is given. So it will get permission denied anyways. So no relevance to the fact that its a seed data.
2. Raising exception in test cases is not the usual practice. We use "assert" statements for that.
3. The logic of opening the seed DB file and searching for "hi" in it is not really serving any purpose here.

Now that I think about it, even if its a seed DB contents, as per the rules we have, SA will be able to delete it. So better avoid this test. But I explained it in detail so that @shimilgithub understand the problems

2022-11-24 04:32 UTC, shimilgithub commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
Shall I replace this inner function call with post and delete methods?

2022-11-24 04:33 UTC, kavitharaju commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
But @shimilgithub you can verify that, if you see DB changes are persisting when you call like this, you can continue using this method. But like Siju said, I also have doubts about it.

2022-11-24 04:35 UTC, kavitharaju commented
@shimilgithub  still there are conflicts

2022-11-24 04:38 UTC, kavitharaju commented
Have you added a test for the following scenario?
- create a language
- create a source entry (Eg; commentry) in that language
- try to delete that language and make sure it gives error saying that "the value is in use and can't be deleted"

2022-11-24 04:39 UTC, shimilgithub commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
When I print response of inner function it returns deleted item id and token of deleted user correctly.

2022-11-24 04:40 UTC, kavitharaju commented on app/test/test_content_types.py
> +    response = test_delete_default_superadmin()
Seeing the "response" is not enough. Need to make sure the DB changes persist

2022-11-29 16:22 UTC, kavitharaju reviewed
The only problem that caught my attention is the introduction of "createdUser" field in response object of Content, Language and even delete API. I dont understand the need for it.

Also the need of column created_user in the deleted_items table.
Rest looks good.

2022-11-30 04:55 UTC, shimilgithub commented
> The only problem that caught my attention is the introduction of "createdUser" field in response object of Content, Language and even delete API. I dont understand the need for it.
> 
> Also the need of column created_user in the deleted_items table. Rest looks good.

Removed createdUser from mentioned places

2022-11-30 07:42 UTC, sijumoncy requested changes

2022-11-30 07:42 UTC, sijumoncy commented on app/test/test_languages.py
> +    assert response.json()['message'] == "Version created successfully"
I think this createVersion fails later , because KJV is a valid one and probably will be in db , Do we have a chance of getting already Exist error on create ? You can use some not common values because this is just for testing.

2022-11-30 07:42 UTC, sijumoncy commented on app/test/test_languages.py
> +    assert response.json()['error'] == 'Already Exists'
Why we get a 409 error . this test is for trying to delete a language which used by another table. and this should be a kind of database error ?
409 - is a kind of create something and tellling us this is already there

2022-11-30 07:42 UTC, sijumoncy commented on app/test/test_languages.py
> +    '''  Negativetest case, trying to delete that language which is used to create a source'''
Do we have similar thing for content types , license, version . those are also part of source creation. Please make sure.

2022-11-30 10:06 UTC, shimilgithub commented on app/test/test_languages.py
> +    '''  Negativetest case, trying to delete that language which is used to create a source'''
done

2022-12-06 14:42 UTC, kavitharaju submitted a review, later dismissed

2022-12-07 05:57 UTC, kavitharaju approved these changes

2022-12-07 06:20 UTC, sijumoncy approved these changes

2022-12-07 06:24 UTC, merged