Feature/delete
Bridgeconn/vachan-api pull request #463
Opened 2022-12-08 04:29 UTC by shimilgithub

committed hard delete on licenses and versions

2022-12-08 13:23 UTC, kavitharaju requested changes
Suggestions have been mentioned only in one place. But when making changes, need to alter all similar cases. Also good to revisit the previous APIs where ever required.

2022-12-08 13:23 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        updateTime = datetime.now())
even if we can't avoid this elif ladder, it would be good if we take the common fields outside.
`createdUser`, `updatedUser`, `updatedTime` etc

2022-12-08 13:23 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +    return deleted_content
I think I have asked this before, but please remind me, why do we need these two variables `deleted_content` and `db_content`? Can't we just use `db_content` itself as return object?

2022-12-08 13:23 UTC, kavitharaju commented on app/routers/content_apis.py
> +    deleted_content = structurals_crud.delete_license(db_=db_, content=delete_obj)
Can we avoid two database access here?
Avoid the first `structurals_crud.get_license_id()`. 
If we try to delete a non existing item I hope database would raise error. If so, we need only one DB access instead of two for deleting.

2022-12-08 13:23 UTC, kavitharaju commented on app/test/test_licenses.py
> +    response = test_post()
I see this test_post() is a long test case, line 95 to 195, which does several positive and negative tests. I dont see any reason to rerun all of that just so we get the output of one response. It will slow down our tests which are already taking too long to run. Better to have a new function(not test function) that does one successful post operation and returns the response

2022-12-08 13:23 UTC, kavitharaju commented on app/test/test_licenses.py
> +        "contentType": "commentary",
For creating source and version here there might be functions you can import from those tests. Worth taking a look there. Eg: look at the commentary tests and see how required version and source are created there by importing functions. Helps with handling the URLs, in case we change them. Keeping URLs in minimum places helps.

2022-12-12 04:15 UTC, shimilgithub commented on app/routers/content_apis.py
> +    deleted_content = structurals_crud.delete_license(db_=db_, content=delete_obj)
@kavitharaju  If I remove structurals_crud.get_license_id() ,it shows the following error.(Error - 502)

  "error": "Database Error",
  "details": "Class 'builtins.NoneType' is not mapped"

Is that fine?

2022-12-12 05:27 UTC, shimilgithub commented on app/routers/content_apis.py
> +    deleted_content = structurals_crud.delete_license(db_=db_, content=delete_obj)
Error message doesn't seems to be meaningful. It would be better if we keep both database accesses.

2022-12-12 12:40 UTC, kavitharaju commented on app/routers/content_apis.py
> +    deleted_content = structurals_crud.delete_license(db_=db_, content=delete_obj)
Agreed. Lets keep it as it is now.

2022-12-12 12:57 UTC, kavitharaju requested changes

2022-12-12 12:57 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        if db_restore.deletedFrom == deleted_from_list[i]:
You could perform this loop and if in one simpler step
```
if db_restore.deletedFrom in deleted_from_list:
  ...
```
And naming the variable `deleted_from_list` something similar to `tables_with_common_fields` or somethings would make more sense to what we are doing.

2022-12-12 12:57 UTC, kavitharaju commented on app/test/test_licenses.py
> +def post_data(): #pylint: disable=missing-function-docstring
Its a very good practice to add a docstring explaing what we do in the function. What looks like obvious to us now, may not seem like that later when we read the code. So add a good docstring that explains briefly what we do here.

2022-12-13 11:24 UTC, kavitharaju requested changes
I see lots of changes that are not related to this task. Looks like it happened with conflict resolution or because of not doing it!
![image](https://user-images.githubusercontent.com/18255929/207305067-6a911a19-91fc-42d3-a15e-5deaa32f8f35.png)

Need to pull changes from version-2. Make sure you keep the changes happened there, unless you have reasons for changing some in relation to the task at hand

2022-12-13 11:24 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +            text("levenshtein(source_token,:word3) < 4").bindparams(word3=word))
May be you made this change upon resolving conflict, but I think the previous is what we need. Need to order the results according to its relevance

2022-12-13 11:24 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +            text("levenshtein(translation,:word3) < 4").bindparams(word3=word))
Same here. Need order_by

2022-12-13 11:24 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +                    token, sent.draftMeta, "untranslated",draft=sent.draft)
This also seems to undo some changes we have made on the version-2. Looks like you are not resolving conflicts properly.

Unless, it was a change you made intenstionally for the task at hand, you should not change what is on version-2

2022-12-13 11:24 UTC, kavitharaju commented on app/crud/nlp_tokenization.py
> +                    print("Meta with confirmed", meta)
Again, issue with conflict resolution. Unnecessary print.

2022-12-13 11:57 UTC, shimilgithub commented on app/crud/nlp_crud.py
> +            text("levenshtein(source_token,:word3) < 4").bindparams(word3=word))
> May be you made this change upon resolving conflict, but I think the previous is what we need. Need to order the results according to its relevance

@kavitharaju These changes are not made by me.These were the changes that happend on latest pull. I didn't committed those on previous PRs.By mistake that happend now. Shall I remove those files which are not modified by me?

2022-12-13 12:33 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +            text("levenshtein(source_token,:word3) < 4").bindparams(word3=word))
Removing the file means delete them from code base? No!
You should only remove the changes. 

What has happened here is, you are un-doing all the changes that were done on version-2 recently by me. We dont want that. What ever changes were done on version-2 after your previous pull should be there.

2022-12-14 04:10 UTC, kavitharaju approved these changes
Looks good to me

2022-12-14 04:37 UTC, merged