committed hard delete on sources
Bridgeconn/vachan-api pull request #471
Opened 2022-12-19 11:10 UTC by shimilgithub

2022-12-20 06:15 UTC, kavitharaju requested changes
Overall this look good and mostly complete. Adding some suggestions and minor changes.

2022-12-20 06:15 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +    '''Fetches row of source id'''
Why define a new get function? Wouldn't it be better to include this provision, to query by id also, into the above `get_sources()` function? To keep things in one place and have polymorphism, rather than defining new functions for each and every usecase.

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_versions.py
>      #Deleting created data
I see small changes like this new line on several files(5 of the total 12 files), which do not have any impact on our task at hand. Its a good practice to not commit these kind of changes to keep the changes minimal and to the point and also avoid later conflicts where it can be avoided.

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_sources.py
> +    headers = {"contentType": "application/json", "accept": "application/json"} #pylint: disable=unused-variable
If this is an unused variable, isn't it better to remove it? When dealing with pylint warnings, our first priority should be to comply with what it suggests. We need to disable only in unavoidable scenarios.

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_sources.py
> +    headers = {"contentType": "application/json", "accept": "application/json"} #pylint: disable=unused-variable
But I see you are running pylint on these test files, and making changes. We were not doing that earlier. I really appreciate the efforts :+1:

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_sources.py
> +    VACHANADMIN = schema_auth.AdminRoles.VACHANADMIN.value #pylint: disable=invalid-name
Same comment here. Try best to comply with their suggestions.

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_sources.py
> +    logout_user(test_user_token)
Its worth adding a GET request also for the source here to ensure the restore was indeed proper.

2022-12-20 06:15 UTC, kavitharaju commented on app/test/test_sources.py
> +        headers=headers_auth)
One more check we could include here is, try a _get commentary call_ 
1. Before delete, which should return proper response
2. After the delete, which should not work
3. After the restore, which should work just as case 1 

to be a little cautious since we are not removing the tables.

2022-12-20 10:35 UTC, shimilgithub commented on app/test/test_sources.py
> +        headers=headers_auth)
> One more check we could include here is, try a _get commentary call_
> 
> 1. Before delete, which should return proper response
> 2. After the delete, which should not work
> 3. After the restore, which should work just as case 1
> 
> to be a little cautious since we are not removing the tables.

I didn't understand what is meant by "get commentary call".Can you please explain bit more?

2023-01-16 13:26 UTC, kavitharaju approved these changes

2023-01-16 13:26 UTC, merged