first two API's
Bridgeconn/vachan-api pull request #475
Opened 2023-01-06 12:32 UTC by Leni-Easo

sending PR for issue#457

2023-01-09 14:14 UTC, sijumoncy requested changes

2023-01-09 14:14 UTC, sijumoncy commented on app/crud/auth_crud.py
> +    if role_description:
There is no meaning in filter a row of table with its description, I don't think its general practice to filter with description. You can change the query param to a search field and try partial or text search for fields like description , app, role

2023-01-09 14:14 UTC, sijumoncy commented on app/routers/auth_api.py
> +    * role Id, role name fields are mandatory
this is a post request and how roleId will be a field

2023-01-09 14:14 UTC, sijumoncy commented on app/routers/auth_api.py
> +    * role Id, role name fields are mandatory
Make this description meaningful enough for a user

2023-01-09 14:14 UTC, sijumoncy commented on app/routers/auth_api.py
> +    log.info('In App Registration')
this is a rore section. right ?

2023-01-09 14:14 UTC, sijumoncy commented on app/schema/schema_auth.py
> +class RoleIn(BaseModel):
roles and roleIn looks similar . why we need 2 schema ?

2023-01-09 15:31 UTC, Leni-Easo commented on app/crud/auth_crud.py
> +    if role_description:
Ok

2023-01-09 15:31 UTC, Leni-Easo commented on app/routers/auth_api.py
> +    * role Id, role name fields are mandatory
ok, will correct it

2023-01-09 15:36 UTC, Leni-Easo commented on app/schema/schema_auth.py
> +class RoleIn(BaseModel):
will check it

2023-01-20 02:39 UTC, sijumoncy requested changes

2023-01-20 02:39 UTC, sijumoncy commented on app/auth/api-permissions.csv
> +/V2/access/roles,PUT,VachanAdmin,False,access-control,edit
Why you added these permission maps here. These are old files and we no longer using this . This kept for just a reference to work on auth for apps. No need to add here

2023-01-20 02:39 UTC, sijumoncy commented on app/routers/auth_api.py
> +@router.get('/v2/access/roles',response_model=List[schema_auth.RoleReadResponse],
is it possible to re use the _RoleOut_ schema here in response instead of a new schema _schema_auth.RoleReadResponse_

2023-01-20 02:39 UTC, sijumoncy commented on db/csvs/auth_resource_types.csv
> +access-control,"application related Roles"
add a more clear description : the access control refer a set of endpoints which are used for the access-control of vachan engine

2023-01-20 02:48 UTC, Leni-Easo commented on app/auth/api-permissions.csv
> +/V2/access/roles,PUT,VachanAdmin,False,access-control,edit
Ok, will remove that

2023-01-20 02:53 UTC, Leni-Easo commented on app/routers/auth_api.py
> +@router.get('/v2/access/roles',response_model=List[schema_auth.RoleReadResponse],
both are same but in RoleReadResponse, roleDescription as optional field

2023-01-20 02:54 UTC, Leni-Easo commented on db/csvs/auth_resource_types.csv
> +access-control,"application related Roles"
Ok

2023-01-20 07:58 UTC, sijumoncy commented on app/routers/auth_api.py
> +@router.get('/v2/access/roles',response_model=List[schema_auth.RoleReadResponse],
why we are putting description as optional field in response . if no response in input will give none value in the response . right ?

2023-01-20 11:04 UTC, Leni-Easo commented on app/routers/auth_api.py
> +@router.get('/v2/access/roles',response_model=List[schema_auth.RoleReadResponse],
yes

2023-01-24 05:08 UTC, kavitharaju reviewed
This PR doesn't have PUT right?

2023-01-24 05:08 UTC, kavitharaju commented on app/crud/auth_crud.py
> +    generate_roles()
This generate_roles() is called to refresh the values kept in-memory that are read from the Db right? I notice this function is called 
- before commit or flush, so will the newly added role be present in the read values?
- before auth verification in the decorator, so would it cause issues if called and API actually fails duw to permission error?
@sijumoncy also

2023-01-24 05:11 UTC, sijumoncy commented on app/crud/auth_crud.py
> +    generate_roles()
yes , it only have post and get

2023-01-24 05:17 UTC, sijumoncy commented on app/crud/auth_crud.py
> +    generate_roles()
yes ,that's right we need to move this call to some where in the auth module , where we success authenticating and commit . This may need to think a logic. 
I am not tried yet. this may work

- need to this function (may be other functions in other apis ) to rename in a general name  and add to dbcontent
- check for  the function name present in the db content where we do commit (success auth) and call it from there

2023-01-24 05:23 UTC, kavitharaju commented on app/crud/auth_crud.py
> +    generate_roles()
sounds good. I like the idea of having a common named function. We can add one more item in the return object of crud along with `db_content` and the others we have now. Need not put it within `db_content` though. 

In the delete APIs we had to do something similar. [here](https://github.com/Bridgeconn/vachan-api/blob/6f989c8cfede11151a6f9f587dc5adfafef1a03f/app/auth/authentication.py#L302). You can think of a better and uniform way to handle these cases alike.

@shimilgithub also

2023-01-30 15:05 UTC, kavitharaju approved these changes

2023-01-30 15:07 UTC, kavitharaju commented
@sijumoncy your approval is required to merge this

2023-01-30 15:10 UTC, sijumoncy approved these changes

2023-01-30 15:26 UTC, merged