Apis for Auth Permission
Bridgeconn/vachan-api pull request #478
Opened 2023-01-13 13:05 UTC by sijumoncy

- Get, Post , put apis for auth permission
- No test cases implemented. Tested manually

2023-01-16 03:59 UTC, kavitharaju requested changes

2023-01-16 03:59 UTC, kavitharaju commented on app/crud/auth_crud.py
> +        query = query.filter(text("to_tsvector('simple', permission_name || ' ' ||"+\
I wonder if searching like this is case sensitive.

2023-01-16 03:59 UTC, kavitharaju commented on app/crud/auth_crud.py
> +    if details.permissionDescription:
Is there a reason why we are not allowing editing the permission name? Do we use it anywhere in DB without FK referencing?

2023-01-16 03:59 UTC, kavitharaju commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
Would "/v2/access/permissions" be more appropriate? This is permission GET, PUT and POST are not specific to an app, right?

2023-01-16 03:59 UTC, kavitharaju commented on app/routers/auth_api.py
> +    search_word: str = Query(None, example="operation"),
Some other filters with which a user would want to query would be,
apps using this permission, endpoints requiring this permission etc.

2023-01-16 03:59 UTC, kavitharaju commented on app/schema/schema_auth.py
> +                "permissionDescription": "permission to create-data"
"Permission to make POST calls making new entries to server DB" would make better senses to the user and this example will encourage VA to also provide more descriptive descriptions.

2023-01-16 04:38 UTC, sijumoncy commented on app/crud/auth_crud.py
> +    if details.permissionDescription:
No there is no specific reason for that , according to the initial discussion we are not allowing to edit contents like appname, rolename, permissionname etc. 
No, permissions will be used in permission-map and access-rules both are FK.

2023-01-16 04:41 UTC, kavitharaju commented on app/crud/auth_crud.py
> +    if details.permissionDescription:
Then it would be good to allow editing of name too. I can image that it would take some time for the users to get a hang of how to name things properly. So scenarios where they want to change the names may occur.

2023-01-16 04:43 UTC, sijumoncy commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
yes , thats right.
Out all endpoints are named in this way v2/app .... 
Thats why I asked in the chat (solution for schema issue) . can we use everything as v2/auth/.... , because all are connected with auth. 
or else we can proceed endpoints like
* app : v2/app/register ....
* roles : v2/app/roles
* permission : v2/access/permission 
* map : v2/auth/permission-map
* accessRules : v2/access/rules

2023-01-16 04:49 UTC, kavitharaju commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
We have been calling this module "auth" and we are used to it. But actually auth is what Kratos does and this is more of "access-control". 
Roles are not for Apps right? Its for users. 
So, how about we changes the endpoints this way.
- v2/app/register
- v2/access/roles
- v2/access/permissions
- v2/access/permission-map
- v2/access/rules
And add tag "access-control" for all the above APIs except app/register which should be auth itself.

2023-01-16 04:49 UTC, sijumoncy commented on app/routers/auth_api.py
> +    search_word: str = Query(None, example="operation"),
does that means , appName or endpoint filter return all the permission details that connected via permission map. right ?

2023-01-16 04:52 UTC, kavitharaju commented on app/routers/auth_api.py
> +    search_word: str = Query(None, example="operation"),
Yes. If you think GET api of permission-map is a better place to do that, I would agree. Just that we need a provision to do such filters somewhere.

2023-01-16 04:53 UTC, sijumoncy commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
that means all the 15-16 apis comes under single section ?

2023-01-16 04:54 UTC, sijumoncy commented on app/routers/auth_api.py
> +    search_word: str = Query(None, example="operation"),
yes , that may be the better place to do that

2023-01-16 04:55 UTC, kavitharaju commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
They are all tightly connected with the concept of "access" right? So its good to link them so and put under a single section.

2023-01-16 04:57 UTC, kavitharaju commented on app/routers/auth_api.py
> +@router.get('/v2/app/permissions',response_model=List[schema_auth.PermissionOut],
If you want you can provide multiple tags, so that there will be smaller groups and one big group.

2023-01-16 10:07 UTC, sijumoncy commented on app/crud/auth_crud.py
> +        query = query.filter(text("to_tsvector('simple', permission_name || ' ' ||"+\
No, This not case sensitive
![case-sensitive](https://user-images.githubusercontent.com/72241997/212652346-fecd227c-c2d2-4082-88a2-621bb43ba2a3.png)

2023-01-19 04:12 UTC, kavitharaju commented
@sijumoncy , are the changes finished on this PR? Ready to be reviewed again?

2023-02-03 07:59 UTC, sijumoncy commented
# New Changes Done
- seed db changes to python script with auto seed on app start if db not exist .

2023-02-07 04:22 UTC, shimilgithub commented on app/crud/auth_crud.py
> +        updatedUser=user_id,
Does updatedUser also need to be assigned to user_id?

2023-02-07 04:31 UTC, sijumoncy commented on app/crud/auth_crud.py
> +        updatedUser=user_id,
on the initial go , both are same. right . Does that break anything ?

2023-02-07 05:01 UTC, shimilgithub commented on app/crud/auth_crud.py
> +        updatedUser=user_id,
Does updatedUser means the one who does modification over ceratedUser's data?So will it be None initially?

2023-02-07 05:06 UTC, sijumoncy commented on app/crud/auth_crud.py
> +        updatedUser=user_id,
yes , right.

2023-02-10 09:19 UTC, kavitharaju approved these changes

2023-02-10 09:20 UTC, merged