Feature/delete
Bridgeconn/vachan-api pull request #482
Opened 2023-01-18 10:08 UTC by shimilgithub

Following files are modified by me in this PR

-  auth/api-permissions.csv
- auth/authentication.py
- crud/contents_crud.py
- db_models.py
- routers/content_apis.py
- schema/schema_content.py
- test/test_dictionaries.py

2023-01-19 04:10 UTC, kavitharaju commented
@shimilgithub, this PR contains implementation of DELETE apis for commentary and dictionary, right?

2023-01-19 04:24 UTC, shimilgithub commented
> @shimilgithub, this PR contains implementation of DELETE apis for commentary and dictionary, right?
Yes Hard delete for commentary and dictionary

2023-01-19 04:38 UTC, kavitharaju requested changes

2023-01-19 04:38 UTC, kavitharaju commented on app/auth/authentication.py
> +                if (method == "DELETE" and "source" in endpoint):
Don't we need to refresh the dynamic tables lookup after a restore too?

2023-01-19 04:38 UTC, kavitharaju commented on app/auth/authentication.py
> +                    db_models.map_all_dynamic_tables(db_= next(get_db()))
Try to form one if statement for all required cases rather than repeating the same steps in different blocks. 

BTW, does deleting rows from these tables require re-loading of table names in the dynamic tables object?

2023-01-19 04:38 UTC, kavitharaju commented on app/crud/contents_crud.py
> +from custom_exceptions import NotAvailableException, TypeException, AlreadyExistsException  #pylint: disable=import-error
Disabling import error is okay. Otherwise it might show warining on your IDE, but the way we are running pylint these wont cause linter errors. So its not mandatory to disable them. But okay if you do it too

2023-01-19 04:38 UTC, kavitharaju commented on app/crud/contents_crud.py
> +def get_commentaries(db_:Session, *args,**kwargs): #pylint: disable=too-many-locals
Why would there be too many locals error here? I dont see new variables introduced in the changes? 

But for the record,ry best to avoid disabling such warnings. See if we can comply as much as possible.

2023-01-19 04:38 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    '''Fetches row of commentary id'''
Can we avoid creating a new function for this and use the existing get_commentaries() to do the job. I had made this suggestion before and made the change myself if the sources PR. Please refer that and copy that pattern. 

I am saying this because we dont want new new functioned defined for every new atomic need. Then the number of functions will grow too much and we will have trouble keeping track of what all features we already have and not have. We used to do it that in V1. Thats hard to maintain in the long run, with different developers working together.

2023-01-19 04:38 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    '''Fetches row of dictionary id'''
Same comment as above. Use get_dictionary() method itself.

2023-01-19 04:38 UTC, kavitharaju commented on app/db_models.py
> +        {'extend_existing': True}
What is the use of this extend_existing ? I am asking because I dont know/remember.

2023-01-19 04:38 UTC, kavitharaju commented on app/schema/schema_content.py
>      verseStart: int = None
I wonder if we should add createdUser info also here...

2023-01-19 05:21 UTC, shimilgithub commented on app/schema/schema_content.py
>      verseStart: int = None
> I wonder if we should add createdUser info also here...

Authentication is getting passed always without createdUser.

2023-01-19 05:36 UTC, shimilgithub commented on app/db_models.py
> +        {'extend_existing': True}
> What is the use of this extend_existing ? I am asking because I dont know/remember.

During delete ,it returns a database error on metadata instance and asked to specify extend_existing=True

2023-01-19 07:49 UTC, kavitharaju commented on app/schema/schema_content.py
>      verseStart: int = None
Its not a technical requirement but a bussiness logic need that I am thinking of.
Supose user A wants to delete a row. He tries and gets a permission denied error, because he was not the createdUser. Now he needs to delete it and dont know who should he ask to do it. But its okay for now. returning that info with every row is going to be make the response object too big. We can have it in GraphQL later

2023-01-19 07:51 UTC, kavitharaju commented
> Yes Hard delete for commentary and dictionary
That is the first thing you needed to mention in the PR comment. Or in the title. Its okay now, saying this for future use.

2023-01-19 07:59 UTC, shimilgithub commented on app/auth/authentication.py
> +                if (method == "DELETE" and "source" in endpoint):
> Don't we need to refresh the dynamic tables lookup after a restore too?

Added dynamic table update after  restore

2023-01-20 06:08 UTC, kavitharaju requested changes
As per our chat discussion, shall wait till you get to do this change as well.

> I see you are adding created user field for each row. I understand it is for checking access. How about using the createdUser of the whole source to authenticate instead of doing it row specific. I think that is how we are doing it in PUT APIs.

2023-01-20 06:08 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    verse: int = None,last_verse: int=None,active: bool= True,
Use kwargs, like before and  please dont disable this pylint warning. You can add commentary_id as a new kwarg

2023-01-20 06:08 UTC, kavitharaju commented on app/crud/contents_crud.py
> +        return query.offset(skip).limit(limit).all()
The pattern we follow is not to run query (.`all()`)) and have return statements in between in these crud functions but do it at the end after applying all possible filters. I think the same pattern will be harmless to use here. Its just for sticking to the same and a cleaner coding style.

2023-01-20 06:08 UTC, kavitharaju commented on app/crud/contents_crud.py
> +        return query.offset(skip).limit(limit).all()
Same comment as above. Try to run the query and return only at the end

2023-01-20 06:08 UTC, kavitharaju commented on app/routers/content_apis.py
> +    commentary_id: int= Query(None, example=100000),
It is not mandatory to have id in the router, because you added it in crud.

2023-01-20 06:08 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    verse: int = None,last_verse: int=None,active: bool= True,
Oh, are you doing this to avoid too-many-locals warning?

2023-01-20 06:09 UTC, kavitharaju commented on app/routers/content_apis.py
> +    commentary_id: int= Query(None, example=100000),
But no harm in adding. Just telling so you know.

2023-01-20 06:24 UTC, shimilgithub commented on app/crud/contents_crud.py
> +    verse: int = None,last_verse: int=None,active: bool= True,
> Oh, are you doing this to avoid too-many-locals warning?

Yes.Shall I pass commentary_id  as kwargs?will it increase local variable count?

2023-01-20 06:28 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    verse: int = None,last_verse: int=None,active: bool= True,
Try that and see. I personally think local-valraibles number is more toleratable than arguments.

2023-01-25 05:15 UTC, kavitharaju requested changes

2023-01-25 05:15 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +    else:
Dont copy source_created user value here, use the user from the details of request. Suppose userX created the item and then super admin came in and deleted something. when we later examine the DB we will see userX did it, when he didn't. That's incorrect info.

2023-01-25 05:15 UTC, kavitharaju commented on app/test/__init__.py
> +
This function gets called in almost all test files and it would flood our terminal with print statement. Better to remove them

2023-01-25 05:15 UTC, kavitharaju commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
Can you double check that restore is indeed included? I see you've resolved the conversation But not see it here

2023-01-25 06:01 UTC, shimilgithub commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
> Can you double check that restore is indeed included? I see you've resolved the conversation But not see it here

restore test returns 404 error when this endpoint is added.Else it works fine

2023-01-25 06:06 UTC, kavitharaju commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
I dont get the reason behind 404 error here. How would that happen, if we add an if condition?

Do we have tests to check the following

1. add a source(commentary)
2. Add some content in it
3. delete the source
4. restore the source
5. Acces the added content via GET.

I am afraid this may not work smoothly if we dont refresh the dynamic tables list here.

2023-01-25 06:16 UTC, shimilgithub commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
> I dont get the reason behind 404 error here. How would that happen, if we add an if condition?
> 
> Do we have tests to check the following
> 
> 1. add a source(commentary)
> 2. Add some content in it
> 3. delete the source
> 4. restore the source
> 5. Acces the added content via GET.
> 
> I am afraid this may not work smoothly if we dont refresh the dynamic tables list here.

these tests are done in test_sources and works fine with and without adding "restore" endpoint in auth. But it raises NotAvailableException(f'{source_name} not found in database in test_commentaries.

I didn't get much clarity on it

2023-01-25 06:21 UTC, kavitharaju commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
Does point 5 work or throws the error you mentioned? It should work successfully as we restored it.

2023-01-25 06:45 UTC, shimilgithub commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
> Does point 5 work or throws the error you mentioned? It should work successfully as we restored it. I think that check on "restore" is required for it work.

Yes. point 5 also returns 404 error.

2023-01-25 07:30 UTC, kavitharaju commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
You mean it throws error in the current implementation, right? ie, without including the if option for restore in endpoint. 
Then need to fix it.

2023-01-25 07:44 UTC, shimilgithub commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
> You mean it throws error in the current implementation, right? ie, without including the if option for restore in endpoint. Then need to fix it.

It fails in both cases.with and without restore endpoint

2023-01-25 08:52 UTC, kavitharaju commented on app/auth/authentication.py
> +                    if (method == "DELETE" and "source" in endpoint):
Well then it needs fixing then.

2023-01-30 15:12 UTC, kavitharaju commented on app/auth/authentication.py
> +                # if (method == "DELETE" and "source" in endpoint) or "restore" in endpoint:
I see you've removed this code, which I don't fully understand. but Shall approve and merge for now. This may need reversal before we finish other DELETEs.

2023-01-30 15:14 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    dictionary_createduser = source_db_content.updatedUser
What are you using `source_db_content.updatedUser` instead of the `user_id` available in this API call?
My concern is, wouldn't this value be the user_id of the user for did the previous update, instead of the current user?

2023-01-30 15:21 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        deleted_user = user_details['user_id']
Why would you need a special check for SuperAdmin. Also I dont see the need for this `if-else` checks at all. I did so in my code, because I didn't want to change the portions you did and also didn't wanted to break the existed tests you had. But I think this should be
```
deleted_user = user_details['user_id']
```
without any kind of checks. Then you can get rid of the arguments `source_createduser` and `item_createduser` altogether. If you have any counter arguments, please do share, though.

2023-01-30 15:24 UTC, kavitharaju reviewed
I think there are changes required. But I am open to hearing your side. So please clarify or proceed with the changes

2023-01-31 03:34 UTC, shimilgithub commented on app/auth/authentication.py
> +                # if (method == "DELETE" and "source" in endpoint) or "restore" in endpoint:
ok

2023-01-31 04:14 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +        deleted_user = user_details['user_id']
> Why would you need a special check for SuperAdmin. Also I dont see the need for this `if-else` checks at all. I did so in my code, because I didn't want to change the portions you did and also didn't wanted to break the existed tests you had. But I think this should be
> 
> ```
> deleted_user = user_details['user_id']
> ```
> 
> without any kind of checks. Then you can get rid of the arguments `source_createduser` and `item_createduser` altogether. If you have any counter arguments, please do share, though.

If I set "`deleted_user = user_details['user_id']"` and " `dictionary_createduser = user_id`", test delete returns 200 for all the users and noauth.Following is happening when I execute inside router
eg : Delete Dictionary(no auth)
1.delete dictionary function executed
2.Add deleted item executed
3. user_details['user_id']: None   and  resp_obj.createdUser: None.  
4. This validates the check_right in authentication like this.
   ```
if "resourceCreatedUser" in required_rights  and \
                user_details['user_id'] == resp_obj.createdUser:
                print("user_details['user_id']:",user_details['user_id'])
                print("resp_obj.createdUser:",resp_obj.createdUser)
                valid = True
```
                
 Same thing happens for other unauthorized users also

2023-01-31 04:25 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        deleted_user = user_details['user_id']
1. You should not overwirte the createdUser value in the sources. That should be updated only once when the dictionary itself is created.
2. The authentication should be happening using the createdUser of sources table and not that of deletedItems table.
     For that, I think you can change the return object of this function this way
```
return {
        'db_content':db_content,
        'source_content':source_row
        }
```
:warning: Do verify the proper syntax, variable names etc and use this method appropriately here. I am just sharing the overall logic.

2023-01-31 05:11 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +        deleted_user = user_details['user_id']
> 1. You should not overwirte the createdUser value in the sources. That should be updated only once when the dictionary itself is created.
> 2. The authentication should be happening using the createdUser of sources table and not that of deletedItems table.
>    For that, I think you can change the return object of this function this way
> 
> ```
> return {
>         'db_content':db_content,
>         'source_content':source_row
>         }
> ```
> 
> warning Do verify the proper syntax, variable names etc and use this method appropriately here. I am just sharing the overall logic.

Do I need to split "`add_deleted_item`"  function into two? One for content types,languages etc, which does not have `source_content` to return and other one for dictionaries,commentaries etc. with above mentioned return object?

2023-01-31 05:20 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        deleted_user = user_details['user_id']
Oh... try doing it with an `if`, if possible. If its complicated, go for separate functions :+1:

2023-01-31 15:55 UTC, kavitharaju requested changes
Looks like you have messed up the conflict resolution. If I merge this, upon merging to the version-2 you will undo several of the bug fixes I have done there. These changes are required. Please dont remove them.

2023-01-31 15:55 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        'source_content':del_content
I wonder how passing language or version object as `source_content` will be treated in the auth module. But as tests work I shall approve this.

2023-01-31 15:55 UTC, kavitharaju commented on app/test/test_agmt_translation2.py
> -def test_empty_draft_initalization():
Did you do conflict resolution properly? Why is this test deleted?

2023-01-31 15:55 UTC, kavitharaju commented on app/test/test_agmt_translation2.py
> -     "sentence": "Oru jungle allathe mattellam tharjima illatha thettu vaakkukal mathram."}
Why are these changes deleted?

2023-01-31 15:55 UTC, kavitharaju commented on app/test/test_translation_suggestions.py
> -    '''testing bug fix for issue #412'''
More changes that are being deleted upon conflict resolution.

2023-01-31 15:55 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +            text("levenshtein(source_token,:word3) < 4").bindparams(word3=word))
Again undoing changes I had made.

2023-02-01 03:04 UTC, shimilgithub commented
> Looks like you have messed up the conflict resolution. If I merge this, upon merging to the version-2 you will undo several of the bug fixes I have done there. These changes are required. Please don't remove them.

This was happened on latest pull which was done before the first commit of this thread.Some tests were not working(not the part I modified) without adding this files in git.And it was not showing any conflict. Thats why I mentioned files which are modified by me in comment.

Do I need to pull again from version-2 and send PR?

2023-02-01 03:51 UTC, joelthe1 commented
Don't have full context here but I'd recommend doing a pull with rebase to
overcome such headaches partially.

On Tue, Jan 31, 2023, 7:04 PM shimilgithub ***@***.***> wrote:

> Looks like you have messed up the conflict resolution. If I merge this,
> upon merging to the version-2 you will undo several of the bug fixes I have
> done there. These changes are required. Please don't remove them.
>
> This was happened on latest pull which was done before the first commit of
> this thread.Some tests were not working(not the part I modified) without
> adding this files in git.And it was not showing any conflict. Thats why I
> mentioned files which are modified by me in comment.
>
> Do I need to pull again from version-2 and send PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bridgeconn/vachan-api/pull/482#issuecomment-1411390966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB7NINXWIALQFFHP4Q4PLRTWVHHEJANCNFSM6AAAAAAT64HZ7I>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-02-02 09:01 UTC, kavitharaju approved these changes

2023-02-02 09:01 UTC, merged