Added PUT API for Roles
Bridgeconn/vachan-api pull request #483
Opened 2023-01-20 10:44 UTC by Leni-Easo

sending PR for issue#457

2023-01-20 11:34 UTC, sijumoncy requested changes

2023-01-20 11:34 UTC, sijumoncy commented on app/routers/auth_api.py
> +@router.put('/v2/access/roles',response_model=schema_auth.RoleUpdateResponse,
is this same response schema that used as response schema in post, get api PR. Is not try to reuse the same schema

2023-01-20 11:34 UTC, sijumoncy commented on app/routers/auth_api.py
> +    * Roles should be registered one
I did not get , what mean by _Roles should registered one_. Try to add docs with more clarification

2023-01-20 11:34 UTC, sijumoncy commented on app/schema/schema_auth.py
> +class RoleUpdateResponse(BaseModel):
create role also have same type of  schema . right ?

2023-01-20 11:45 UTC, Leni-Easo commented on app/routers/auth_api.py
> +@router.put('/v2/access/roles',response_model=schema_auth.RoleUpdateResponse,
I used different schema for PUT not the one use in POST & GET

2023-01-20 11:50 UTC, Leni-Easo commented on app/routers/auth_api.py
> +    * Roles should be registered one
In this I mean try to avoid the repetition of the roles. will correct it.

2023-01-20 11:51 UTC, Leni-Easo commented on app/schema/schema_auth.py
> +class RoleUpdateResponse(BaseModel):
yes

2023-01-31 15:57 UTC, kavitharaju approved these changes

2023-01-31 17:28 UTC, sijumoncy approved these changes

2023-02-01 08:44 UTC, merged