hard delete on bible books
Bridgeconn/vachan-api pull request #498
Opened 2023-02-07 05:36 UTC by shimilgithub

2023-02-07 15:14 UTC, sijumoncy requested changes

2023-02-07 15:14 UTC, sijumoncy commented on app/crud/contents_crud.py
> +    db_content2 = query2.filter(model_cls.book_id == model_cls2.book_id).first()
is this model_cls.bookId or db_content.bookId ? 
model class is the dynamic table contains multiple books..... ?
line 897 is to fetch all the rows of the cleaned bible of the book same as the single row of orginal usfm  deleting from dynamic bible table ?

2023-02-07 15:14 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
I did not get the logic completely on restore orginal and cleaned bible tables .
I saw one db content is adding to the db . what about the second table ?
Do we using a logic of restore bible and cleaned with the usfm original data from the deleted table

2023-02-07 15:14 UTC, sijumoncy commented on app/routers/content_apis.py
> +    del_clean=structurals_crud.add_deleted_data(db_=db_,del_content=deleted_content['db_content2'],#pylint: disable=unused-variable
is this really required to store cleaned data too in the db ?

2023-02-08 02:56 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
When we delete a row from the dynamic table of bible,associated cleaned table data also gets deleted along with it and both of them will be added to deleted_items table.
Hence during restore,same happens.That is, cleaned table data also will be restored when we restore the bibles table,

2023-02-08 02:59 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
> I did not get the logic completely on restore orginal and cleaned bible tables . I saw one db content is adding to the db . what about the second table ? Do we using a logic of restore bible and cleaned with the usfm original data from the deleted table

When we delete from the dynamic table of bible,associated cleaned table also getting deleted and both of them will be added to deleted items table.

Hence during restore also same happens.Cleaned table will be restored along with associated bibles table restore

2023-02-08 03:11 UTC, shimilgithub commented on app/routers/content_apis.py
> +    del_clean=structurals_crud.add_deleted_data(db_=db_,del_content=deleted_content['db_content2'],#pylint: disable=unused-variable
> is this really required to store cleaned data too in the db ?

This would be the better way since we are accumulating all the deleted contents in a single table.That would be easy for future reference also.
It won't take extra space since we are just moving item from one table to another.
Also when we restore bibles,this cleaned table will automatically restored back which won't take much headache.

Instead of adding cleaned table item into deleted items table and restore,we can delete it and perform insert instead of restore.That  again need to generate ref_id ,split data and convert to usfm format etc. which I felt unnecessary since we already have that  info.

This is my thought.Please let me know if its not feasible.

2023-02-08 03:11 UTC, shimilgithub commented on app/crud/contents_crud.py
> +    db_content2 = query2.filter(model_cls.book_id == model_cls2.book_id).first()
> is this model_cls.bookId or db_content.bookId ? model class is the dynamic table contains multiple books..... ? line 897 is to fetch all the rows of the cleaned bible of the book same as the single row of orginal usfm deleting from dynamic bible table ?

Yes. Thats right. Resolved issue

2023-02-08 04:35 UTC, sijumoncy commented on app/routers/content_apis.py
> +    del_clean=structurals_crud.add_deleted_data(db_=db_,del_content=deleted_content['db_content2'],#pylint: disable=unused-variable
ok. Moving cleaned tables from cleaned to delete will effect same storage. make sense

2023-02-08 04:45 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
sorry for asking this again .
on delete I found 2 delete performing for db_content, db_content2 for bible and cleaned respectivily. 
on restore there is only 1 item db_content2 is adding back to db. does this single add will restore both bible and cleaned table in a single restore call for one bible book

2023-02-08 04:48 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
one more doubt , what will happen if I perform the following operation
 - source added
 - bible inserted ( create bible and cleaned )
 - delete bible  (remove bible and cleaned )
 - delete source 
 - try restore bible (bible + cleaned )
 
 does this flow cause any error ?

2023-02-08 04:48 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
> sorry for asking this again . on delete I found 2 delete performing for db_content, db_content2 for bible and cleaned respectivily. on restore there is only 1 item db_content2 is adding back to db. does this single add will restore both bible and cleaned table in a single restore call for one bible book

There are two restore happening only in case of bibles. Line 167 is to restore cleaned table and line 171 is to restore bibles.

2023-02-08 04:51 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
> > sorry for asking this again . on delete I found 2 delete performing for db_content, db_content2 for bible and cleaned respectivily. on restore there is only 1 item db_content2 is adding back to db. does this single add will restore both bible and cleaned table in a single restore call for one bible book
> 
> There are two restore happening only in case of bibles. Line 167 is to restore cleaned table and line 171 is to restore bibles.

Ok got it .

2023-02-08 05:04 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
> one more doubt , what will happen if I perform the following operation
> 
> * source added
> * bible inserted ( create bible and cleaned )
> * delete bible  (remove bible and cleaned )
> * delete source
> * try restore bible (bible + cleaned )
> 
> does this flow cause any error ?

This will throw an error because we are trying to fetch source details at line 152

2023-02-08 05:08 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
Do we handled it already ? 
for the other endpoints also ?

2023-02-08 05:15 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +            db_.add(db_content2)
> Do we handled it already ? for the other endpoints also ?

In some endpoints like language,content_types we are perform direct delete and restore.
And the others which are associated with source,we are fetching the source name first from the sources table. If source is not available,it will throw error

2023-02-08 11:52 UTC, sijumoncy approved these changes

2023-02-08 12:41 UTC, merged