hard delete on bible audio
Bridgeconn/vachan-api pull request #500
Opened 2023-02-08 12:46 UTC by shimilgithub

Issue #405

2023-02-09 14:44 UTC, sijumoncy requested changes

2023-02-09 14:44 UTC, sijumoncy commented on app/crud/contents_crud.py
> +def get_available_bible_books(db_, source_name,book_code=None, content_type=None,#pylint: disable = too-many-arguments,disable=too-many-locals
too-many-args pylint can be avoided by access bibleaudio_id via kwargs

2023-02-09 14:44 UTC, sijumoncy commented on app/crud/contents_crud.py
> +    if bibleaudio_id:
This is a common fucntion for getting bible content , based on content_type,
what happend if provide content_type other than audio and bibleaudio_id. 
Does this query returns proper response ?

2023-02-09 14:44 UTC, sijumoncy commented on app/crud/structurals_crud.py
> +        if db_restore.deletedFrom.endswith(("audio","cleaned")) is False:
this means the control go to else part when the deleted from not endswith audio or cleaned. 
I saw the audio handled in else case . what about cleaned ?

2023-02-09 14:44 UTC, sijumoncy commented on app/schema/schema_content.py
> +    audioId: int = None
is this really need to make optional ? don't  we get unique id in every request

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    post_response = client.get(UNIT_URL+source_name+"/books?content_type=audio&udio_id"+str(audio_id),headers=headers_auth)
How this test is passed ? 
content_type=audio&udio_id -  wrong param is passed here right ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    post_response = client.get(UNIT_URL+source_name+"/books?content_type=audio&udio_id"+str(audio_id),headers=headers_auth)
is saw the response contain 6 items . The audio id is for book wise or single audio ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    assert not delete_response.json()[0]['audio']['audioId'] == audio_id
do you think , this need to test in a loop because 5 items are in response ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    assert response.status_code == 404
this need to be call an input validation error . 1 input item is missing ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    assert response.status_code == 404
this also to be missing error ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    restore_response =  client.get(UNIT_URL+source_name+'/books?book_code=mat',\
what is the content type here ? audio or all

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    #check item exists in cleaned table
delete and restore audio does affect bible and cleaned ?

2023-02-09 14:44 UTC, sijumoncy commented on app/test/test_bibles.py
> +    restore_response = client.put(RESTORE_URL, headers=headers_auth, json=data)
is this the same data you are passing here as the above one (delete source , restore audio )

2023-02-10 05:02 UTC, shimilgithub commented on app/crud/structurals_crud.py
> +        if db_restore.deletedFrom.endswith(("audio","cleaned")) is False:
> this means the control go to else part when the deleted from not endswith audio or cleaned. I saw the audio handled in else case . what about cleaned ?

On restore, cleaned table  has to be deleted along with bible books only.It should not be removed alone.Thats why that check is kept

2023-02-10 05:12 UTC, shimilgithub commented on app/test/test_bibles.py
> +    #check item exists in cleaned table
No.bible and cleaned has the info about bible books

2023-02-10 05:28 UTC, shimilgithub commented on app/schema/schema_content.py
> +    audioId: int = None
not necessary.removed "None" and resolved

2023-02-10 05:29 UTC, sijumoncy commented on app/schema/schema_content.py
> +    audioId: int = None
check does that make any issue in get bible books

2023-02-10 05:36 UTC, shimilgithub commented on app/test/test_bibles.py
> +    assert response.status_code == 404
Resolved

2023-02-10 05:36 UTC, shimilgithub commented on app/test/test_bibles.py
> +    assert response.status_code == 404
Resolved

2023-02-10 05:41 UTC, shimilgithub commented on app/test/test_bibles.py
> +    restore_response = client.put(RESTORE_URL, headers=headers_auth, json=data)
Did you mean same as "test_restoreitem_with_notavailable_source" ?

2023-02-10 07:51 UTC, sijumoncy commented on app/test/test_bibles.py
> +    restore_response = client.put(RESTORE_URL, headers=headers_auth, json=data)
1695 and 1699

2023-02-10 08:00 UTC, shimilgithub commented on app/test/test_bibles.py
> +    restore_response = client.put(RESTORE_URL, headers=headers_auth, json=data)
> 

yes

2023-02-10 10:19 UTC, shimilgithub commented on app/test/test_bibles.py
> +    restore_response = client.put(RESTORE_URL, headers=headers_auth, json=data)
It should be different.resolved.

2023-02-10 10:23 UTC, shimilgithub commented on app/test/test_bibles.py
> +    restore_response =  client.get(UNIT_URL+source_name+'/books?book_code=mat',\
changed to audio

2023-02-10 10:47 UTC, shimilgithub commented on app/test/test_bibles.py
> +    post_response = client.get(UNIT_URL+source_name+"/books?content_type=audio&udio_id"+str(audio_id),headers=headers_auth)
modified to fetch single item.both issues resolved

2023-02-11 13:53 UTC, sijumoncy approved these changes

2023-02-11 15:26 UTC, merged