Hard delete on Autographa Project and Users
Bridgeconn/vachan-api pull request #510
Opened 2023-03-10 09:43 UTC by shimilgithub

Issue #405

2023-03-13 06:26 UTC, kavitharaju requested changes

2023-03-13 06:26 UTC, kavitharaju commented on app/auth/access_rules.json
> +        "delete":["SuperAdmin", "AgAdmin", "AgUser"],
We shouldn't let any AgUser delete the project. Only projectOwner should be able to delete a specific project. so we need the following
```
"delete":["SuperAdmin", "AgAdmin", "projectOwner"],
```

2023-03-13 06:26 UTC, kavitharaju commented on app/crud/structurals_crud.py
> +        del_item_createduser = deleting_user
I made this change, if I remember correctly. But I did that to temporarily get the code working and to not affect your older APIs. 
We dont want 
```
del_item_createduser = del_content.createdUser
```
This is incorrect info. When we record a transaction, the person who did that action should be recorded. In this case the user who is calling the deleteAPI shoudl be recorded. Not the value from createdUser field.

2023-03-13 06:26 UTC, kavitharaju commented on app/db_models.py
> +            # back_populates="users")
What is the need of this change? I am just asking to understand.

2023-03-13 06:26 UTC, kavitharaju commented on app/routers/content_apis.py
> +            table_name = dbtable_name)
Dont we need to pass the details of current user to be recorded in deleted_items table?

2023-03-13 06:26 UTC, kavitharaju commented on app/routers/content_apis.py
> +            table_name = dbtable_name)
I see same action done on several cases below this. I think passing those `user_details` are needed.

2023-03-13 06:26 UTC, kavitharaju commented on app/routers/content_apis.py
> +            table_name = dbtable_name)
I think it is to be passed as `deleting_user=user_details['user_id']`

2023-03-13 10:42 UTC, shimilgithub commented on app/db_models.py
> +            # back_populates="users")
> What is the need of this change? I am just asking to understand.

This change was there in referred code.

2023-03-14 04:58 UTC, shimilgithub commented on app/db_models.py
> +            # back_populates="users")
reverted changes

2023-03-14 09:19 UTC, kavitharaju commented on app/db_models.py
> +            # back_populates="users")
Is everything working properly after the revert?
I dont remember clearly, but I doubt I might have made this change to fix some issues. Are all tests running correctly on local too?

2023-03-14 09:20 UTC, shimilgithub commented on app/db_models.py
> +            # back_populates="users")
> Is everything working properly after the revert? I dont remember clearly, but I doubt I might have made this change to fix some issues. Are all tests running correctly on local too?

Yes.Everything is working fine

2023-03-14 10:27 UTC, kavitharaju commented on app/db_models.py
> +            # back_populates="users")
alright then

2023-03-14 10:28 UTC, kavitharaju approved these changes

2023-03-14 10:28 UTC, merged