permission map api - Post
Bridgeconn/vachan-api pull request #561
Opened 2023-05-08 10:32 UTC by sijumoncy

- #457 
- endpoint for permission-map POST

2023-05-09 05:49 UTC, kavitharaju requested changes
2 minor suggestions. But good to clear them so that we don't forget

2023-05-09 05:49 UTC, kavitharaju commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
Seeing the long list of imports from the same file I wonder if using it as follows would be better
```
import crud.auth_crud as auth_crud
...
auth_crud.create_auth_permission(..)
```

2023-05-09 05:49 UTC, kavitharaju commented on app/routers/auth_api.py
> +    * filterResults permission map allow or not to filter the result (default False ) '''
I think this `filterResults` would need a better explanation... You could add one more sentence to the existing sentence like this...
```
For example for an endpoint that returns a list of items like bibles in the DB, setting this to true is needed to ensure the bibles are filtered based on user's role and the bible's access permissions.
```

2023-05-10 04:54 UTC, sijumoncy commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
you mean, 
Import module and call module.function ?

2023-05-10 05:09 UTC, kavitharaju commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
yes, I think that is better than the long list of import we have now. But if pylint has a different opinion do as it says :)

2023-05-10 09:16 UTC, kavitharaju commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
On second thoughts... may be just keep the import in multiple lines like this
```
from crud.auth_crud import create_auth_permission, update_auth_permission
from crud.auth_crud import get_auth_permission, create_role, get_role, update_role, create_access_rules
from crud.auth_crud import update_access_rules, get_access_rules, create_permission_map
```
Code looks cleaner and no need to repeat the module name all over the code.

2023-05-10 13:54 UTC, joelthe1 commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
To add another opinion, I usually do something like this:
```
from crud.auth_crud import (
    create_auth_permission,
    update_auth_permission,
    get_auth_permission,
    create_role, get_role, 
    update_role, 
    create_access_rules,
    update_access_rules, 
    get_access_rules, 
    create_permission_map,
)
```
```

2023-05-11 08:32 UTC, sijumoncy commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
> auth_crud

I think pylint won't allow multi import from same ( use group import )

2023-05-15 07:38 UTC, kavitharaju commented on app/routers/auth_api.py
> +    update_access_rules, get_access_rules, create_permission_map
Multiple import is using different libraries in same like this ` import os, re` right?

Our case is importing multiple things from same sub module. [Here](https://nickjanetakis.com/blog/comparing-3-ways-to-import-multiple-things-from-the-same-python-module) I see someone else thinking through the same options we are considering. 

I just brought it up because the present one looked like a clutter and wanted something visually 'neat'. 
```
from crud.auth_crud import create_auth_permission, update_auth_permission
from crud.auth_crud import get_auth_permission, create_role, get_role, update_role, create_access_rules
from crud.auth_crud import update_access_rules, get_access_rules, create_permission_map
```
The above method will give a _somewhat_ tidier approach without making the file too long
 ```
from crud.auth_crud import (
    create_auth_permission,
    update_auth_permission,
    get_auth_permission,
    create_role, get_role, 
    update_role, 
    create_access_rules,
    update_access_rules, 
    get_access_rules, 
    create_permission_map,
)
```
This one on the other hand keeps it much more well organized, at the cost of more lines. This has the added advantage that we can easily comment out few of the imports without much hassle while we are coding/debugging etc

2023-05-29 05:06 UTC, kavitharaju approved these changes

2023-05-31 05:19 UTC, merged