Add VE Installation Error Troubleshooting documentation
Bridgeconn/vachan-api pull request #582
Opened 2023-05-31 09:46 UTC by AthulyaMS

2023-06-01 03:58 UTC, shimilgithub requested changes
Document appears to be misaligned. Please ensure that each bullet point is properly indented for better readability. Also use backticks  to highlight commands and code snippets or use code blocks to distinguish them from regular text.

2023-06-01 16:35 UTC, kavitharaju requested changes

2023-06-01 16:35 UTC, kavitharaju commented on docs/VE_Installation_Error_Troubleshooting.md
> +﻿<a name="_int_4nblkg51"></a>**ERRORS OCCURED DURING VACHAN-API INSTALLATIONS**
What is `<a name="_int_4nblkg51"></a>`. I see this through out the document

2023-06-01 16:35 UTC, kavitharaju commented on docs/VE_Installation_Error_Troubleshooting.md
> +﻿<a name="_int_4nblkg51"></a>**ERRORS OCCURED DURING VACHAN-API INSTALLATIONS**
`ERRORS OCCURED DURING VACHAN-API INSTALLATIONS` could be re-phrased `Solutions for errors you may encounter during Vachan-api setup`, because our focus is the solutions.

2023-06-01 16:35 UTC, kavitharaju commented on docs/VE_Installation_Error_Troubleshooting.md
> +<a name="_int_11bhbt1q"></a>**Solution** : sudo apt install python3-venv
I wonder, how did you get the error if you didn't have venv installed in the first place?
Or did you mean `sudo apt install python3-dev` or something else like that?

2023-06-01 16:35 UTC, kavitharaju commented on docs/VE_Installation_Error_Troubleshooting.md
> +`    `<https://itslinuxfoss.com/install-pgadmin-ubuntu-22-04/>
Links can be either given plainly or using the format `[text](url)` in markdown

2023-06-05 07:25 UTC, shimilgithub requested changes
You can add other issues you faced like `Docker daemon not running`.Please go through our discussions once again and include if anything is missed.

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 1) E: Unable to locate git packages
Remove `E` from all errors

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 2) E: Unable to correct problems you have broken packages
change to ` Issues with Broken Packages`

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +   - `sudo apt install git`
why to install `git` here?

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +   - `sudo apt-get install git`
here also.

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 3) The virtual environment was not created successfully because ensurepip is not available.Failing command: ['/home/athulya/vachan-api/vachan-ENV/bin/python3', '-Im', 'ensurepip', '--upgrade', '-
I don't this this is an installation error.

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +   `sudo apt install pgadmin4-desktop`
Does installing `desktop mode` only will resolve this problem?

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +GRANT ALL PRIVILEGES ON DATABASE databasename TO user;
this line not required

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +Provide a new valid email address for the superadmin account that you haven't used in earlier installations. Make sure the password contains a combination of uppercase, lowercase, special characters,
Rewrite similar way
```
1. Provide a new valid email address as SuperAdmin username.
2. Ensure that your password incorporates a combination of uppercase and lowercase letters, special characters and numbers.
3. Avoid using passwords that closely resemble your username
```

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 11) Command not found
You can remove this

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 12) File not found
Remove this

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 11) Command not found
not required

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 12) File not found
not required

2023-06-05 07:25 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +Provide a new valid email address for the superadmin account that you haven't used in earlier installations. Make sure the password contains a combination of uppercase, lowercase, special characters,
Rewrite in similar way as below
```
1. Provide a valid email address for the SuperAdmin username
2. Ensure that your password incorporates a combination of uppercase and lowercase letters, special characters, and numbers.
3. Avoid using passwords that closely resemble  your username

```

2023-06-05 11:31 UTC, shimilgithub requested changes

2023-06-05 11:31 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 6) Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get [http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version](http://%2Fvar%2Frun%2Fdocker.soc
We can give some meaningful name for URL

2023-06-05 11:31 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +- Tried to install usfm-grammar in the initial part of installation.
You can consider removing this line as well. Or mention "install usfm-grammar before installing any other package in case there are any installation issues with it".

2023-06-05 11:31 UTC, shimilgithub commented on docs/VE_Installation_Error_Troubleshooting.md
> +### 3) The virtual environment was not created successfully because ensurepip is not available.Failing command: ['/home/athulya/vachan-api/vachan-ENV/bin/python3', '-Im', 'ensurepip', '--upgrade', '-
remove your name from path. use like this `~/vachan-api/...`

2023-06-08 02:39 UTC, kavitharaju approved these changes
Looking much better :+1:

2023-06-08 03:15 UTC, shimilgithub approved these changes

2023-06-08 03:16 UTC, merged