Fastapi upgradation and removing Graphql Module
Bridgeconn/vachan-api pull request #591
Opened 2023-06-16 06:19 UTC by AthulyaMS

- #589

2023-06-16 11:57 UTC, shimilgithub requested changes
Few code segments are repeated in many places. Try to reuse the same code

2023-06-16 11:57 UTC, shimilgithub commented on app/test/test_agmt_translation.py
> +    data_str2 = json.dumps(post_obj_list)
if `data_str` and `data_str` is assigned to same value, you don't need two assignment statements. Use the first one itself

2023-06-16 11:57 UTC, shimilgithub commented on app/test/test_agmt_translation.py
> +    data_str3= json.dumps(post_obj_list)
This statement also can be remove

2023-06-16 11:57 UTC, shimilgithub commented on app/test/test_agmt_translation.py
> +        data_str4= json.dumps(post_obj_list)
here also

2023-06-16 11:57 UTC, shimilgithub commented on app/test/test_agmt_translation.py
> +        },
you can reuse same code segment .no need to repeat

2023-06-18 06:25 UTC, shimilgithub requested changes
Please incorporate suggestions not only in the commented place but also consistently across the code wherever you encounter the same code pattern.

Also can see follwing warning is `test bibles`.
```
/app/app/crud/contents_crud.py:897: SAWarning:SELECT statement has a cartesian product between FROM element(s) "table_xxx_audio" and FROM element "table_xxx".  Apply join condition(s) between each element to resolve.
    fetched = query.filter(model_cls.active == active).offset(skip).limit(limit).all()
```
Remove that too  by using `join operation` to avoid memory leaks in future.

2023-06-18 06:25 UTC, shimilgithub commented on app/test/test_agmt_translation.py
> +        },
Still  `data_str` and `params` are redefined multiple times. You don't need to do that if  it contains same information. Define only once and call the same variable wherever it is required.

2023-06-26 04:27 UTC, shimilgithub approved these changes, later dismissed

2023-06-26 04:53 UTC, kavitharaju requested changes
I see the `graphql_api` folder is still maintained even though the contents are removed. You can remove the folder too

2023-06-26 04:53 UTC, kavitharaju commented on app/test/test_agmt_projects.py
>          '&user_id='+str(user_id),headers=headers_auth)
I see this change consistently in tests... Can you explain the context here?
I dont see any change corresponding to this in router functions, also I see `client.get()` is still used in tests, so what is the need of changing these tests?

2023-06-26 04:53 UTC, kavitharaju commented on app/test/test_agmt_translation.py
>      assert len(response.json()) > 0
Here also can you explain what is happening?
What is the differrence between the following 
 - params=...
 - json=...
 - params={'data':...}
 Which is for query params and which for body params? I see all these being used over different tests? If all these are supported what is the need for the change?

2023-06-26 05:39 UTC, AthulyaMS commented
> I see the `graphql_api` folder is still maintained even though the contents are removed. You can remove the folder too

When folders completely deleted,there was showing some linting error in the module ,while running in repo .

2023-06-26 05:52 UTC, AthulyaMS commented on app/test/test_agmt_projects.py
>          '&user_id='+str(user_id),headers=headers_auth)
While ruuning tests ,there was showing error " TestClient.delete() got an unexpected keyword argument 'json'. In a documentation ,i had seen ,If we want to send a body with a DELETE method, we can replace client.delete(...) by client.request(...) .By using this ,the test passed.
![202516125-8bd3c9b1-bb98-44a2-9415-6a837badc15f](https://github.com/Bridgeconn/vachan-api/assets/119833248/a775866a-ac1c-45a4-adb8-b1525ff0eb9d)

2023-06-26 06:07 UTC, AthulyaMS commented on app/test/test_agmt_translation.py
>      assert len(response.json()) > 0
Here also ,while running ," TestClient.get() got an unexpected keyword argument 'json'.  The data_str variable is created by serializing a list of Python objects (post_obj_list) into a JSON-formatted string using the json.dumps() function. This JSON string is then included as a parameter in an HTTP GET request. By modifying like this ,test passed

2023-06-26 06:30 UTC, kavitharaju commented on app/test/test_agmt_translation.py
>      assert len(response.json()) > 0
Looking at the GET `/token-translations` API, I see it doesn't need a body parameter passed at all. It must have been a mistake in that test. I guess it can just be removed.

2023-06-26 06:31 UTC, kavitharaju commented on app/test/test_agmt_translation.py
>      assert len(response.json()) > 0
Please check if there are other GET call tests where body params are passed unnecessarily and fix them if you can.

2023-06-26 06:33 UTC, kavitharaju commented
> When folders completely deleted,there was showing some linting error in the module ,while running in repo .

There might be linter run on that module. You can change the command for running the linter excluding that folder. And update it on `.githubworkflows/...` CI/CD pipeline to avoid that error on gitactions.

2023-06-26 06:34 UTC, kavitharaju commented on app/test/test_agmt_projects.py
>          '&user_id='+str(user_id),headers=headers_auth)
This is a work around for passing a `json` to delete. We would rather have the recommended standard of not using the body params in delete, than this work-around.

2023-06-30 10:05 UTC, AthulyaMS commented
#605

2023-06-30 10:28 UTC, kavitharaju approved these changes

2023-06-30 10:30 UTC, kavitharaju commented
> > When folders completely deleted,there was showing some linting error in the module ,while running in repo .
> 
> There might be linter run on that module. You can change the command for running the linter excluding that folder. And update it on `.githubworkflows/...` CI/CD pipeline to avoid that error on gitactions.

I see the empty `graphql_api/` folder is still there. Remember to try the above suggestion in next PR. Good to add an issue for tracking this too, if we cant get to it immediately

2023-06-30 10:30 UTC, merged