adding makefile
Bridgeconn/vachan-api pull request #601
Opened 2023-06-26 10:36 UTC by Joel-Joseph-George

- #574

2023-06-26 11:09 UTC, shimilgithub requested changes

2023-06-26 11:09 UTC, shimilgithub commented on makefile
> +	@echo ">>> Activated virtual environment."
Incorrect display string. Make it as `Virtual environment configured`

2023-06-26 11:09 UTC, shimilgithub commented on makefile
> +	@echo ">>> Virtual environment activation:"
Too many `echo` commands not required. You can remove this.

2023-06-26 11:09 UTC, shimilgithub commented on makefile
> +		echo "Some packages are missing or failed to install."; \
If any package got failed in installation, will it mention which package it was?

2023-06-26 11:09 UTC, shimilgithub commented on setup.sh
> +echo 'export VACHAN_POSTGRES_PASSWORD="password"' >> ~/.bashrc
postgres password also read it from terminal

2023-06-26 11:09 UTC, shimilgithub commented on setup.sh
> +read -p "Please enter to open .bashrc file and make neccessary changes and click save"
Change to `Press Enter to make necessary changes in .bashrc file and Click save`

2023-06-26 11:09 UTC, shimilgithub commented on makefile
> +	sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='vachan_db'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE vachan_db"
Also I think you need to add installation command for `postgres` before creating db.

2023-06-26 11:09 UTC, shimilgithub commented on setup.sh
> +read -r -p "Enter a strong password for the super admin: " super_password
Also in short  mention criteria fdor selecting superadmin username and password. Refer [this](https://github.com/Bridgeconn/vachan-api/pull/582/files#diff-6a151f2caecf99ec67c86d83d7bcf58f6491d4dfada4a8efd3924ccedda81f4eR81-R83)

2023-06-26 11:20 UTC, Joel-Joseph-George commented on makefile
> +		echo "Some packages are missing or failed to install."; \
no, its just to make sure if all the packages from requirements.txt is installed or not.

2023-06-27 10:48 UTC, shimilgithub approved these changes, later dismissed

2023-06-27 14:12 UTC, kavitharaju commented on makefile
> +	sudo apt install postgresql postgresql-contrib
Shouldn't we handle postgres version requirement here?
There might be specific version we need. like 15 or above... What is there is already an older postgres installed? I guess the `apt install` without `--upgrade` will not change anything then. 
But putting `--upgrade` like that may be risky too... what is the user has other projects that needs his current version...
So how to go about this?

2023-06-27 14:12 UTC, kavitharaju commented on makefile
> +	sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Here also I wonder if we should specify versions

2023-06-27 14:12 UTC, kavitharaju commented on setup.sh
> +gedit ~/.bashrc
why do we need to open this in gedit? I wonder how this will work out when you try this on a terminal-only environment, like our VMs now. 
If you want to show the new content something like `tail -n 12 ~/.bashrc` will be a more widely supported tool.

2023-06-27 14:20 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt install postgresql postgresql-contrib
so we can either set like an readme before running this makefile to ensure if the user have pre-installed some softwares. The softwares that i m thinking is :-
- psql
- docker

-Also for setting up new Vm i gotta add pip and venv commands also.

So the user need to install these prerequite softwares themselves before running the makefile. Thats an option .

i m open to suggestions if we can make it inside the makefile too.

2023-06-27 14:23 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
yeah we can mention if we need an particular docker version to be installed.. Right now its going with latest version of docker.

Also docker is something maybe users are already working on another project. so overwriting may cause issues

2023-06-27 14:24 UTC, Joel-Joseph-George commented on setup.sh
> +gedit ~/.bashrc
with the help of gedit we can confirm our changes before saving it.. but yeah can remove it we want.

2023-06-28 03:52 UTC, kavitharaju commented on makefile
> +	sudo apt install postgresql postgresql-contrib
Here is what I can think of, for things like postgres and docker...
First check if these are already installed and get their versions. If its below our required version, inform the user about it and ask if they want to continue using the existing version or upgrade? Based on their response take action. 
This way we are not doing anything without users consent, and also letting him know of potential version conflict, so later get can figure out issues that may raise due to this.

2023-06-28 03:57 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt install postgresql postgresql-contrib
I understood what you meant and i can try .. But i m not sure how exact it can be implemented. Right now i was trying to check whether the new vm has pip3 or python3-venv installed already  or if not then proceed with installing.. but whatever code i m writing its bypassing it and installing..

2023-06-28 04:04 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt install postgresql postgresql-contrib
btw is there any other software shall i be concered about otherthan docker and psql? usfm-grammer or like that?

2023-06-28 04:08 UTC, kavitharaju commented on makefile
> +	sudo apt install postgresql postgresql-contrib
USFM-Grammar could be another candidate. But we are planning to get rid of that node version and keep only the python version of usfm-grammar which will come only within the virtual environment. So, lets not worry about that now.

2023-06-28 04:09 UTC, kavitharaju commented on makefile
> +	sudo apt install postgresql postgresql-contrib
But for now, until the python version is ready to be used like that, continue installing node version the way we do now, globally...

2023-06-28 04:28 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt install postgresql postgresql-contrib
ok noted

2023-06-29 07:11 UTC, Joel-Joseph-George commented on setup.sh
> +gedit ~/.bashrc
hey kavitha. Here is my suggestion for .bashrc. we can so gedit because it can help us on like an 2nd confirmation from the user before saving the file.

but on trial running on vm , we cant confirm .bashrc becasue it wont be opened on vm. so maybe we can use tail command.. i m looking for an opinion from you.

2023-06-29 07:12 UTC, Joel-Joseph-George commented on makefile
> +	sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
hey kavitha. so right now i have made an code section for docker that will install latest docker versions .. aka 24.0.2. So is it okay if the user is going with that version. ?

2023-06-29 07:51 UTC, kavitharaju commented on makefile
> +	sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Good to pin to 24.0.2, or something we have tested our app on. Later versions could bring in breaking changes and at that time our make file will install those unsupported latest version.

2023-06-29 12:32 UTC, kavitharaju commented on setup.sh
> +gedit ~/.bashrc
But writing to the file using `>>` already writes it there, without checking user's permission, right? Its not like we are confirming before saving.... But I see your point, it gives user a chance to correct things if he wants.

But I am leaning towards `tail` because it will be supported in more systems. But not strongly opinionated either... 
You choose. :)

2023-06-30 05:51 UTC, Joel-Joseph-George commented on setup.sh
> +gedit ~/.bashrc
Hey kavitha, Well i have given a try for tail command as you said.. yeah it will work on terminal perfectly.. but the issue will be since you know makefile is an long setup and the editing of bashrc actually is in middle of the process.. so after the user click enter to save the changes. the tail command wil show and atm the next command will come and probably its gonna go faster that user wont have time to even notice or check the password or anything.. 

![Screenshot from 2023-06-30 11-14-13](https://github.com/Bridgeconn/vachan-api/assets/64024835/50d6a146-f05b-4936-b2b1-15d1fb315e3d)

you can see for yourself.after the changes its suddenly going to install usfm-grammer. 

Personally i m leaning to gedit cause the user can save and adjust the bashrc visually by themselves and have an confirmation.. But this will be only usefull if the user is having an normal ubuntu machine .. 

What i wanna ask is what wil be our usecase most because if its having an normal ubuntu machine ; then  gedit will work fine and will be better.. but if the vm is used mostly then we can go ahead with tail... anyway look for your thought on this.

Ty ;)

2023-06-30 08:52 UTC, kavitharaju commented on setup.sh
> +gedit ~/.bashrc
I agree witth you. We expect it to be used mostly on UI machines.. so lets go ahead with gedit

2023-07-03 04:14 UTC, shimilgithub requested changes
To ensure proper formatting, please remove the green and ash-colored vertical lines visible throughout in the view mode of this markdown file. Also use codeblocks if you are writing multiple comands one after other. Refer README file for syntax.

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +- Makefile
Remove this

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +### **_Steps_**
Step 1 :Initializing and Setting Up 'vachan-api' Repository

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +## Set up locally for development and testing
Set up Vachan Engine locally for development and testing

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +>Fork the repo into your github account and then use the terminal to clone the repository on your local machine with the following steps
mention command for   clone . Refer [here](https://github.com/Bridgeconn/vachan-api/tree/version-2) and follow same order and procedure for initial  set up

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +so with this you can run the makefile easily.
remove this part

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +## Things going on in Makefile
Step 2 : Installing and Executing Makefile

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +With this command the makefile will run and as the setup process goes on it will ask permission from yourself which you have to give by yourself.
"During the execution of this command, the Makefile will initiate and prompt for your permission at various stages of the setup process, which you will need to provide manually."

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +
**"Important Considerations: Key Points to Remember During Makefile Execution**"

When running the Makefile, it is crucial to keep a few things in mind. As the Makefile automates the installation process, in case it halts midway, you have the option to rerun that particular process without restarting the entire Makefile. Consequently, I will provide you with specific commands for each process, allowing for more targeted execution and troubleshooting.

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +_Some things to note_
Important points to remember

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +* Avoid using passwords that closely resemble  your username
Remove green color background showing in view and keep these three points in italics

2023-07-03 04:14 UTC, shimilgithub commented on installation.md
> +### If the make file doesn't work or you cant run it properly you can try our mannual method and you can find it on README.md
"In case the Makefile fails to work or encounters issues during execution, an alternative option is to follow our manual method. Detailed instructions for the manual setup can be found in the README file."

Also  give link to README

2023-07-03 05:48 UTC, Joel-Joseph-George commented on installation.md
> +so with this you can run the makefile easily.
well we  need to install make to run the makefile.

2023-07-04 03:40 UTC, shimilgithub approved these changes, later dismissed

2023-07-04 04:28 UTC, kavitharaju reviewed
What is the status of testing on VM?

2023-07-04 04:28 UTC, kavitharaju commented on makefile
> +	fi
When installing manually, did you guys also had to do `sudo apt install python3-dev` or such system dependencies?

2023-07-04 04:29 UTC, kavitharaju commented
And, why was docker installation and check removed?

2023-07-04 04:32 UTC, Joel-Joseph-George commented on makefile
> +	fi
while working in vm , i realized there is no pip and venv installed.. so i thought of adding it as an pre-requisite to the makefile..it will check whether its installed or not.. seems like an good thing to have.. because if there is no venv and pip3 , the makefile will be forced to fail on the virtual env creation

2023-07-04 04:44 UTC, Joel-Joseph-George commented
> And, why was docker installation and check removed?

well actually it was working, but the issue was its installaing 24.0.2 which is the latest version.. and i tried to install the version which we preferred , ie 24.0.1. but it almost messed my system.. so i thought of leaving the docker because from my personal view. the docker will be something the user can install themselves maybe? i m not sure. or we can go ahead it 24.0.2 or the latest docker.. this code will work fine on maybe already installed docker.. for new machines 

![Screenshot from 2023-07-04 10-13-36](https://github.com/Bridgeconn/vachan-api/assets/64024835/c1817c0d-5387-41c6-a555-7b9259b469a0)

these steps also need to be doing which i m not sure how it will go in the makefile. i m kinda scared to mess my system again .

2023-07-04 04:48 UTC, kavitharaju commented
Yes, I would expect that trying out things like this could mess up your system. Hence we gave you the VM  :)

If everything works fine with 24.0.2, go ahead and pin it to that version. We used 24.0.1 because that was the latest when we tried and tested things out. No other reason. But being able to say which is the version we have tested things with and are recommending is important. So pin to .2.

2023-07-04 05:15 UTC, Joel-Joseph-George commented
> Yes, I would expect that trying out things like this could mess up your system. Hence we gave you the VM :)
> 
> If everything works fine with 24.0.2, go ahead and pin it to that version. We used 24.0.1 because that was the latest when we tried and tested things out. No other reason. But being able to say which is the version we have tested things with and are recommending is important. So pin to .2.

well after all this code, i m not sure about running the docker installation in makefile.. there is a lot chance that this can messup who ever installing the setup and then they need to do it mannually cos i have tried the code in makefile and its not installing perfectly. mostly because installing docker needs some pre-requsite to add some repositry key and things and its not working finely on vm too.. 

the code right now that i have # is just to uninstall old version and install new version.. but it will be only applicable to local machines that have docker already installed

2023-07-04 05:51 UTC, kavitharaju commented
I would suggest, that you give it a try to run required prior steps and docker installation also in make file. Just give it one more attempt. The reason why we are automatic this much is to "do not scare away" new users. "Docker" seems to be the most scary word to new comers, as far as I have seen... :laughing: 

And if you are still not able to get it working, may be do a check to find out if docker is there and if it is the required version or above., If not, indicate that to users and provide link to installation instruction. This is a last resort.

2023-07-04 07:47 UTC, Joel-Joseph-George commented
> I would suggest, that you give it a try to run required prior steps and docker installation also in make file. Just give it one more attempt. The reason why we are automatic this much is to "do not scare away" new users. "Docker" seems to be the most scary word to new comers, as far as I have seen... 😆
> 
> And if you are still not able to get it working, may be do a check to find out if docker is there and if it is the required version or above., If not, indicate that to users and provide link to installation instruction. This is a last resort.

okay so i have the code to run the docker installation.. and seems its fine .. but i m not so sure about it will turn out.. the code seems installing in the vm. and checking version seems 24.0.2(latest) . but i m not that sure with the code.. kinda having an feeling this maybe mess up the system when installing.. also i only tried it in vm for my own safety.. anyway i will provide the code below.. if it seems okay i can update the pr

installing-docker:
	@if docker --version | grep -q "24.0.2"; then \
		echo "You already have Docker 24.0.2 installed."; \
	else \
		read -p "Do you want to install/update Docker 24.0.2? (y/N) " response; \
		if [[ $$response =~ ^[Yy]$$ ]]; then \
			if docker --version | grep -q "Docker version"; then \
				echo "Removing existing Docker installation..."; \
				for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $$pkg; done; \
			fi; \
			echo "Installing Docker 24.0.2..."; \
			sudo apt-get update; \
			sudo apt-get install -y ca-certificates curl gnupg; \
			sudo install -m 0755 -d /etc/apt/keyrings; \
			curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg; \
			sudo chmod a+r /etc/apt/keyrings/docker.gpg; \
			echo "deb [arch=$$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null; \
			sudo apt-get update --allow-releaseinfo-change; \
			sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; \
			if [[ $$? -eq 0 ]]; then \
				echo "Docker 24.0.2 has been installed/updated."; \
			else \
				echo "Docker installation/update failed. Refer to the Docker installation documentation for manual installation: https://docs.docker.com/engine/install/debian/"; \
			fi; \
		else \
			echo "Docker 24.0.2 installation/update canceled."; \
		fi; \
	fi
![Screenshot from 2023-07-04 13-16-07](https://github.com/Bridgeconn/vachan-api/assets/64024835/7bb20fa5-9523-4ee1-a53c-cbf8eba9a891)
Looking for your thought on this.. and about the links i dont know when it will expire.

2023-07-04 08:06 UTC, kavitharaju commented
I dont see you specifying docker version when installing
>  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; 

or before that, other than in print comments

2023-07-04 08:09 UTC, Joel-Joseph-George commented
> I dont see you specifying docker version when installing
> 
> > sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin;
> 
> or before that, other than in print comments

tbh i couldnt find the correct way to install docker with an specified version.. only thing i could find was the way with installling the latest version.. all the other code i tried was not installing the specified version and mostly messed up system and vm. this was the one which i could pull from that.. but yeah it will only go for latest.

2023-07-04 08:21 UTC, kavitharaju commented
Can you install it manually? Or couldn't figure out how to do it manually either?

I see a usage like this
```
sudo apt-cache policy docker-engine
sudo apt-get install docker-engine=1.13.1-0~ubuntu-xenial
```
in [this article](https://medium.com/@gauravsj9/how-to-install-specific-docker-version-on-linux-machine-d0ec2d4095)

In some places I see usage of a KEY. Are these things you already tried out?

2023-07-04 08:30 UTC, Joel-Joseph-George commented
> Can you install it manually? Or couldn't figure out how to do it manually either?
> 
> I see a usage like this
> 
> ```
> sudo apt-cache policy docker-engine
> sudo apt-get install docker-engine=1.13.1-0~ubuntu-xenial
> ```
> 
> in [this article](https://medium.com/@gauravsj9/how-to-install-specific-docker-version-on-linux-machine-d0ec2d4095)
> 
> In some places I see usage of a KEY. Are these things you already tried out?

well i couldnt find it.. thats why my local is running 24.0.2. and when i tried like changing it to 24.0.1, it messed up big time.. 

anyway i read nd tried from that article.. which is mentioning of adding the key and packages then install the docker.. i have already added those commands to my code, 

but i couldnt connect it to install a certain specified package. which i dont know how..

2023-07-04 08:34 UTC, kavitharaju commented
If you have tried your best and want to give up, lets settle with the latest then.
But make sure you change the print comments accordingly and not mislead the user. Tell him the actual version that was installed.

2023-07-04 08:36 UTC, Joel-Joseph-George commented
well right now we can only say 24.0.2

but its only until docker release new version.. which i cant say 

or maybe i can say it like installing new docker version maybe instead of 24.0.2

2023-07-04 08:38 UTC, kavitharaju commented
You can get the version after installation using `docker --version`. Display that output to user

2023-07-04 08:39 UTC, kavitharaju commented
And ask for "upgradation" only if version is lower than 24.0.1. This version or higher, which is already present could be left untouched.

2023-07-04 08:51 UTC, Joel-Joseph-George commented
> And ask for "upgradation" only if version is lower than 24.0.1. This version or higher, which is already present could be left untouched.

okay so i have made some tweaks.. this is wil check if the user is preinstalled with 24.0.1 or 24.0.2 which will go to else statement..
![Screenshot from 2023-07-04 14-19-40](https://github.com/Bridgeconn/vachan-api/assets/64024835/924aa4dd-95f6-4cf3-b397-9a7c4be3d3c6)

if they arent it will possible install the docker.. which should  work i guess.. right now i cant unsinstall docker from vm. so it worked at first.. second onwards its showing its already installed ..seems fine.. here is the tweaked code for you supervision ..


installing-docker:
	@if docker --version | grep -q "Docker version 24.0."; then \
		echo "You already have Docker 24.0.1 or above installed."; \
	else \
		read -p "Do you want to install/update Docker 24.0.2? (y/N) " response; \
		if [[ $$response =~ ^[Yy]$$ ]]; then \
			if docker --version | grep -q "Docker version"; then \
				echo "Removing existing Docker installation..."; \
				for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $$pkg; done; \
			fi; \
			echo "Installing Docker 24.0.2..."; \
			sudo apt-get update; \
			sudo apt-get install -y ca-certificates curl gnupg; \
			sudo install -m 0755 -d /etc/apt/keyrings; \
			curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg; \
			sudo chmod a+r /etc/apt/keyrings/docker.gpg; \
			echo "deb [arch=$$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null; \
			sudo apt-get update --allow-releaseinfo-change; \
			sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; \
			if [[ $$? -eq 0 ]]; then \
				echo "Docker 24.0.2 has been installed/updated."; \
			else \
				echo "Docker installation/update failed. Refer to the Docker installation documentation for manual installation: https://docs.docker.com/engine/install/debian/"; \
			fi; \
		else \
			echo "Docker 24.0.2 installation/update canceled."; \
		fi; \
	fi

2023-07-04 09:58 UTC, kavitharaju commented
Need to change 24.0.2 from follwoing places and replace it with `latest`
1. `Do you want to install/update Docker 24.0.2? (y/N) "`
2. `echo "Installing Docker 24.0.2..."; `
3. `echo "Docker 24.0.2 has been installed/updated."; `
4. `echo "Docker 24.0.2 installation/update canceled.";`
And any other such usages which can become incorrect with later releases of Docker.

2023-07-04 10:01 UTC, kavitharaju commented on makefile
> +	else \
In the comment it was checking for "24.0." accomodating .1 and .2. It would say we should accommodate all 24.x s

2023-07-04 10:03 UTC, Joel-Joseph-George commented on makefile
> +	else \
i m sorry we okay with versions of 24 right?

2023-07-04 13:28 UTC, kavitharaju approved these changes
This will require us to make changes once docker moves to the next minor version. But for now lets keep it this way

2023-07-04 13:28 UTC, merged