new resource parascripturals
Bridgeconn/vachan-api pull request #632
Opened 2023-07-12 10:46 UTC by shimilgithub

- #623 
- Removed infographics and bible videos

2023-07-13 14:18 UTC, kavitharaju requested changes
Sharing my thoughts after a partial review. Tests and routers have not been reviewed.

2023-07-13 14:18 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    parascript_id=kwargs.get("parascript_id",None)
It would be required to have filtering options based on all available fields of parascripturals. 
- metadata
- reference: Not only for exact match, also for ranges. For example if table has a range, Gen 1:1 to Gen 1:20, then a query with Gen 1:5 should return the row
- content: Something like string contains. That is not exact match but sub string match or search option just on this field
- and any more fields we have included in parascripturals

2023-07-13 14:18 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            row.content = item.content
We would need this unicode normalization for all text fields, where we may get values in other languages. Like title, description, content etc.

2023-07-13 14:18 UTC, kavitharaju commented on app/db_models.py
> +    content = Column('content', String)
Since we have active field in all other tables, good to keep it just for consistency

2023-07-13 14:18 UTC, kavitharaju commented on app/db_models.py
> +    paratype = Column('paratype',String)
This would need a better name. If `type` can't be used can we use either `content_type`(the older content type we had is going to be called resource_type, so that name is free I think) or `category` may be. This should be used alike in I/O objects(pydantic models, query params etc) , DB tables and preferably in code too.

2023-07-13 14:18 UTC, kavitharaju commented on app/db_models.py
> -    refIds  = Column('ref_ids', ARRAY(Integer))
I wonder what would be the best way to store the references. 
1. In the deleted biblevideo code, i see we were listing all ref ids as an array. That is not very storage efficient if the ranges will be large.
2. In the current code I see you are using JSONB. That means queries with a verse in between can become super inefficient as we cant perform that query via SQL. but will have to fetch all data to memory and perform that filter some how in python. That is not gonna work out with large tables.
3. One design that comes to my mind is, in I/O objects keep it as a JSON with specified fields. In DB table keep two columns, ref_start and ref_end, which will have the integer presentation of the range boundaries. Now queries can be done using integer comparison of two fields uisng a between operation in SQL. 
Eg:
JSON in input may have fields representing `GEN 1:1` to `GEN 1:25`.
In DB table, `ref_start=1001001` and `ref_end=1001025`. (the bbcccvvv format, but integer values).
A query for verse GEN 1:7 could check if `ref_start <= 1001007 <= ref_end`

2023-07-13 14:18 UTC, kavitharaju commented on app/schema/schema_content.py
> +    link: AnyUrl = None
Reference not included?

2023-07-13 14:18 UTC, kavitharaju commented on app/schema/schema_content.py
> +    reference: dict = None
reference's type should be a class defined separately specifying the inner fields

2023-07-18 08:57 UTC, shimilgithub commented on app/db_models.py
> -    refIds  = Column('ref_ids', ARRAY(Integer))
@kavitharaju  what would be the type of `reference` in I/O objects? Is that a separate `Reference class` with book,chapter,verse fields(as mentioned below)? or a json object having these fields(as mentioned above)

2023-07-18 09:05 UTC, kavitharaju commented on app/db_models.py
> -    refIds  = Column('ref_ids', ARRAY(Integer))
In pydantic, define it as class, so that proper validation of all inner fields will be done. For the user, it would be a JSON with specific fields anyway, right?

2023-07-24 10:16 UTC, kavitharaju commented on app/crud/contents_crud.py
> +    return ref_id
I wonder if we already have this function somewhere. If not, a good place for this in the code base is in utils.py file so that other module can easily find it a use it.

2023-07-24 10:16 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            row.link = item.link
Need to make do the unicode normalization , stripping etc at PUT and POST functions as well. I see you do that in GET while filtering..

2023-07-24 10:16 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            ref = ref["py/state"]["__dict__"]
What is happening here? if you are trying to convert a python dictionary into Pydantic or SQLAlchemy or other kinds of classes, there would be utils function that does that. See if you can either reuse it or re-plicate the logic.

2023-07-24 10:16 UTC, kavitharaju commented on app/crud/contents_crud.py
> +            ref = ref["py/state"]["__dict__"]
If its otherway round, most likely these classes will have `.__dict__()` fucntion to convert them to dictionary.

2023-07-24 10:16 UTC, kavitharaju commented on app/db_models.py
> +    refEnd = Column('ref_end', Integer)
I see you are replicating the same data in JSON and integer format... Good :+1:

2023-07-24 10:16 UTC, kavitharaju commented on app/schema/schema_content.py
> +                "chapterEnd": 10,
In an example in router module, I saw you were showing interger value expected in `bookStart`. I hope we are expecting it to be book code in all IO consistantly..

2023-07-24 10:16 UTC, kavitharaju commented on app/schema/schema_content.py
> +    reference: ParascriptReference = None
This `ParascriptReference` could be given a more generic name like `Reference` and used in other palces too... I can totally see we using the same approach in commentaries soon(ie, if others also like this)

2023-07-24 10:31 UTC, shimilgithub commented on app/schema/schema_content.py
> +    reference: ParascriptReference = None
We already have schema named  [`Reference`](https://github.com/Bridgeconn/vachan-api/blob/API-refactor/app/schema/schema_content.py#L97) . What about `Scripture` or `Annotation`?

2023-07-24 10:38 UTC, kavitharaju commented on app/schema/schema_content.py
> +    reference: ParascriptReference = None
Oh.. what we want is changing that existing Reference into the new format, with across chapter and across book scope. We only need one, that is to be used consistently in all places. 
can you try to do that without hurting things too much? Keep the newly added fields as optional and see if we can rename the existing fields as needed and make subsequent code changes without too much wreckage

2023-07-24 11:55 UTC, shimilgithub commented on app/crud/contents_crud.py
> +            row.link = item.link
does  unicode  normalization is enough for  `title` and `content` fields only?

2023-07-25 04:14 UTC, kavitharaju approved these changes

2023-07-25 04:14 UTC, merged