change terminology
Bridgeconn/vachan-api pull request #634
Opened 2023-07-14 05:47 UTC by Joel-Joseph-George

#608

2023-07-14 06:48 UTC, shimilgithub commented on app/crud/nlp_crud.py
> +    resource = db_.query(db_models.Language).filter(
I think in `translation` module, terminology change is not required unless we are referring the `resources` table. @kavitharaju  can you please confirm this?

2023-07-14 08:38 UTC, Joel-Joseph-George commented on app/crud/nlp_crud.py
> +    resource = db_.query(db_models.Language).filter(
ohh. Just confirm it and will make the changes as per need

2023-07-17 05:50 UTC, kavitharaju commented on app/crud/nlp_crud.py
> +    resource = db_.query(db_models.Language).filter(
Yes, normally `source` in translation module refers to the source of translation as in source ad target. We should not change that to resource

2023-07-21 03:07 UTC, shimilgithub requested changes
few changes required in ` test_agmt_translation2` and `test_smast_translation2` files as mentioned. Also remove the print statements you have kept in between.

2023-07-21 03:07 UTC, shimilgithub commented on app/test/test_agmt_translation2.py
Still you  `resource` and related terms  is used in translation test. it has to be `source` . eg:source_sentences

2023-07-21 03:07 UTC, shimilgithub commented on app/test/test_smast_translation2.py
> +resource_sentences = [
should be `source_sentences`

2023-07-21 03:07 UTC, shimilgithub commented on app/test/test_smast_translation2.py
> +    put_data_resource = {
should be `put_data_source`

2023-07-21 05:56 UTC, shimilgithub approved these changes

2023-07-24 04:00 UTC, merged