content -> resource types ;changes in terminologies
Bridgeconn/vachan-api pull request #659
Opened 2023-08-04 11:16 UTC by Joel-Joseph-George

#619

2023-08-04 12:44 UTC, shimilgithub requested changes
Seems like conflicts are not resolved properly. All updates on new resource "Audio Bible" and test is removed in this PR. Please look into the codebase(API-refactor branch)  while resolving conflicts locally

2023-08-04 12:44 UTC, shimilgithub commented on app/auth/api-permissions.csv
> +/v2/bibles/{resource_name}/audios,DELETE,None,False,None,delete/deactivate
these endpoints,related APIs and tests are already removed in earlier pr. now changes are reverted back

2023-08-04 12:44 UTC, shimilgithub commented on app/auth/api-permissions.csv
> -/v2/resources/bible/audios/{resource_name},DELETE,None,False,None,delete/deactivate
It should be there. These are newly added APIs

2023-08-04 12:44 UTC, shimilgithub commented on app/db_models.py
> -    updateTime = Column('last_updated_at', DateTime, onupdate= ist_time,default=ist_time)
it should be there

2023-08-04 12:44 UTC, shimilgithub commented on app/db_models.py
> +    active = Column('active', Boolean, default=True)
this has to be removed

2023-08-04 12:44 UTC, shimilgithub commented on app/schema/schema_content.py
> -        }
it shoud not be removed

2023-08-08 04:37 UTC, shimilgithub requested changes

2023-08-08 04:37 UTC, shimilgithub commented on app/crud/contents_crud.py
> +    if resource_type == "usfm":
these are data formats and does not belongs to resource_type(eg:bible,commentary,vocabulary etc.). So keep it as `content_type` itself

2023-08-08 04:37 UTC, shimilgithub commented on app/crud/media_crud.py
> +    resource_type = mimetypes.guess_type(url.split("/")[-1], strict=True)
These are formats like `image/jpeg`, `video/mp4`. So keep as `content_type` itself

2023-08-08 04:37 UTC, shimilgithub commented on app/routers/content_apis.py
> +    resource_type: schema_content.BookResourceType=Query(None), active: bool=True,
should not be changed

2023-08-08 04:37 UTC, shimilgithub commented on app/routers/content_apis.py
> +    * returns the JSON, USFM and/or Audio contents also: if resourceType is given
`contentType`

2023-08-08 04:37 UTC, shimilgithub commented on app/routers/filehandling_apis.py
> +        resource_type=schema_content.BookResourceType.USFM,
should not be changed

2023-08-08 04:37 UTC, shimilgithub commented on app/schema/schema_content.py
> +class BookResourceType(str, Enum):
no change

2023-08-08 04:37 UTC, shimilgithub commented on app/test/test_bibles.py
> +    response = client.get(UNIT_URL+resource_name+'/books?resource_type=usfm')
no change

2023-08-08 04:37 UTC, shimilgithub commented on app/test/test_bibles.py
> +    '''add some usfm and test get api based on book_code and active filters '''
`usfm data`

2023-08-08 04:37 UTC, shimilgithub commented on app/test/test_media.py
> +    print("####", response.json())
can be removed

2023-08-08 06:05 UTC, shimilgithub approved these changes

2023-08-08 06:30 UTC, kavitharaju commented on app/auth/authentication.py
> +    if endpoint.endswith(("types", "languages", "licenses", "versions")):
Better give "resources/types" here because there could be other apis in the future ending with types, for instance GET model/types or GET project/types . Better be more explicit.

2023-08-08 06:30 UTC, kavitharaju commented on app/crud/media_crud.py
> +            "Resource-Type": content_type[0]
Isn't this part of HTML header? why are we changing that?

2023-08-08 06:44 UTC, Joel-Joseph-George commented on app/crud/media_crud.py
> +            "Resource-Type": content_type[0]
i think accidently done it

2023-08-08 07:09 UTC, kavitharaju approved these changes

2023-08-08 07:10 UTC, merged