Distinguish translation projects based on Apps
Bridgeconn/vachan-api pull request #665
Opened 2023-08-09 11:40 UTC by shimilgithub

- #442 
- **has database change**
- APIs changed
   - PUT and POST /v2/text/translate/token-based/projects  and filtering in GET 
   - PUT          /v2/text/translate/token-based/project/tokens
   - PUT          /v2/text/translate/token-based/project/token-sentences
   - PUT          /v2/text/translate/token-based/project/draft

2023-08-10 09:09 UTC, kavitharaju requested changes
Converting the field from str to list is going to have impact through out the code, like DB, pydantic schema etc. But mentioned it only in one place

2023-08-10 09:09 UTC, kavitharaju commented on app/crud/projects_crud.py
> +    """Decorator function for ato check app compatibility"""
Does this function have too many statements? I think this comment could be safely removed

2023-08-10 09:09 UTC, kavitharaju commented on app/crud/projects_crud.py
> +        parsed_data = json.loads(json_string)
I dont know if we need to do all this to get the arguments. If its body parameter, it is a kwarg to the function right? It might be accessible from the kwargs.get(<body param name>)

2023-08-10 09:09 UTC, kavitharaju commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
1. Taking `app` value from header and then checking against it is pointless.
2. In 207, I assume we expect the `compatible_with` data to come as input of the function. I hope that input is not coming from user and it is coming from DB. If it is coming from user, it should be treated here as `client_app` and values for `compatible_app` should come from DB.
3. `client_app != compatible_with` should actually be `client_app in compatible_with`. Meaning we need to have a list of apps in `compatible_with`

2023-08-10 09:09 UTC, kavitharaju commented on app/routers/translation_apis.py
> +    compatible_with: schema_auth.App = Query(None,example="SanketMAST"),
Doing this in `get_project()` looks good. One suggestion is , to set it to requesting app, from header if None. Also to make it list.

2023-08-10 09:17 UTC, kavitharaju commented on app/routers/translation_apis.py
>  async def update_draft(request: Request,project_id:int=Query(...,example="1022004"),
Are we using this check for all APIs in translation projects or just a few?

2023-08-10 10:18 UTC, shimilgithub commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
> 1. Taking `app` value from header and then checking against it is pointless.
> 2. In 207, I assume we expect the `compatible_with` data to come as input of the function. I hope that input is not coming from user and it is coming from DB. If it is coming from user, it should be treated here as `client_app` and values for `compatible_app` should come from DB.
> 3. `client_app != compatible_with` should actually be `client_app in compatible_with`. Meaning we need to have a list of apps in `compatible_with`

Point 2 is not clear for me.

`compatible_with` in line 207 comes from user input.

Does taking "compatible_with" value from db will be same as that of the app value in request?Because we are storing in the db only if "compatible_with" value from user input matches "app" value in request.

This is how I implemented.
Initially in POST:
1. we are expecting compatible_with value from user input,if not there, it is set as app in the header
2. If compatible_with from user input = app in the request -> test pass, else fail

2023-08-10 10:18 UTC, shimilgithub commented on app/routers/translation_apis.py
>  async def update_draft(request: Request,project_id:int=Query(...,example="1022004"),
check is given for follow

> Are we using this check for all APIs in translation projects or just a few?

check is done for following APIs
PUT and POST /v2/text/translate/token-based/projects and filtering in GET
PUT /v2/text/translate/token-based/project/tokens
PUT /v2/text/translate/token-based/project/token-sentences
PUT /v2/text/translate/token-based/project/draft

2023-08-10 13:49 UTC, kavitharaju commented on app/routers/translation_apis.py
>  async def update_draft(request: Request,project_id:int=Query(...,example="1022004"),
I can see total 16 APIs there, without counting GET projects and POST project. All the rest can have this check, right?

2023-08-10 16:35 UTC, shimilgithub commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
can i get confirmation on this?

2023-08-11 05:30 UTC, kavitharaju commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
How you are setting it in POST projects is correct. That is, expect user to provide the value to you, if not provided take from header and set that value inn DB.

Now what are we doing this for? For making sure projects are served to only app's that they are compatible with , right? So the details we need for them are two
1. Nature of the project data. Which we should be getting from saved value in DB. That is what i would assign for the "compatible_with" variable in your decorator. So this should not come from user, but from DB, for all apis calls except the one to create it for the first time.
2. The nature of the app making the API call. Which should be obtained from the API calls header. This is what should be called as `client_app` in your code.

More over the `compatible_with` in DB and also here should be a list, not just single string, to accommodate such needs in future.

2023-08-14 13:13 UTC, shimilgithub commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
@kavitharaju I am stucked in below scenario.
```
client_app(app in header) =  SanketMAST
1. POST -> compatiblileWith(user input) = ['SanketMAST','Autographa']
   project created
   db_app(app value stored in db) = ['SanketMAST','Autographa']
2. POST  -> compatible_with = ["VachanAdmin']
   raises error "incomptible app"
3. PUT  -> compatibleWith(user input) = ['Vachanadmin']
   db app = ['SanketMAST','Autographa']
   client_app = ['SanketMAST']
   PROJECT UPDATED since db_app = client app
   Now db_app - ['VachanAdmin']
```
After step 3, I am unable to perform any  other operations(PUT/DELETE) since client_app and db_app are different.

2023-08-14 13:59 UTC, kavitharaju commented on app/crud/projects_crud.py
> +            raise HTTPException(status_code=403, detail="Incompatible app")
In my mind I imagine the PUT in step 3 to be used like this
1. Is we want to add one more app to the existing list, we give the full list ['SanketMAST','Autographa', 'Vachanadmin']
2. If we want to remove one app from the existing list we provide a list without it, but including the rest of the apps already present in the list ['SanketMAST']

2023-08-16 08:29 UTC, kavitharaju requested changes

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
Do we need this if block at all? Wouldn't it work if we just not call the decorator from this API route?

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +            project_row = project_obj.compatibleWith
I see you are making a query with not filter(WHERE clause), which means you are always going to get the first project in the table? is that how you intended this to work? Wont we have project_id specified in POST apis?

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = project_row
In other `elif` blocks I see you are setting the value like this
```
 compatible_with = project_obj.compatibleWith
```
Is using the project row here working properly where as in other places you have the specific field?

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = project_row
Same 2 questions asked above
1. Why the first project from table?
2. Why ` compatible_with = project_row` and not ` compatible_with = project_row.compatibleWith`?

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = project_row
Also I wonder if we really need these different if-elif ladder, based on METHODs, wouldn't the code within `PUT` support call cases where project_id is used?

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
>              raise HTTPException(status_code=403, detail="Incompatible app")
Good to define a custom_exception for this or use one of existing like `PermissionException` instead of the HTTPException.

2023-08-16 08:29 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                project_id = query_params['project_id']
I see that all APIs, other than `PUT projects` and `PUT project/user` uses `project_id` as query parameter consistantly. Would it be good to change these two endpoints also to follow that pattern through out. Then our APIs, aswell as code snippets like this will be much more "neat". What do you think?

2023-08-16 08:29 UTC, kavitharaju commented on app/routers/translation_apis.py
> +        compatible_with = app
Is this working properly? Dont we need `compatible_with = [app]`, as it is list?

2023-08-16 16:26 UTC, shimilgithub commented on app/crud/projects_crud.py
> +                compatible_with = project_row
before line 225,`project_row` is assigned to  `project_obj.compatibleWith`

2023-08-18 05:31 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
Here again in the else part I fear you are taking the value of `compatible_with` from user(either header or args) and in next step comparing it against itself.
Why do we need a an else for project_id is not None. Which senario will reslut in that need where we dont have project information to check against?

2023-08-18 06:05 UTC, shimilgithub commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
@kavitharaju  `else`  part will execute only if `project` id is `None` and there is no `compatibleWith`(or compatibleWith is empty) field in the  `body param` of request.

This will be happening only for POST project APIs without compatibleWith field in the request body.

- PUT and DELETE  and POST user will pass through the condition at line 222 since `project_id` is mandatory there.
-  In POST, project
    -  if we are mentioning `compatibleWith` field in the request body,it will go to condition at line 227
    - if `compatibleWith` field not mentions, whatever in the app header will be assigned to it.(which is the else part at line 229)

2023-08-18 06:09 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
I thought we are not calling this check from POST project API. I dont see why that would mae sense, to do a check when a new project is created fresh.

2023-08-18 06:15 UTC, shimilgithub commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
Won't it be good to have the header app in `compatibleWith` list initially?

2023-08-18 06:23 UTC, kavitharaju commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
Alright, I leave it to you, even though I dont quite see the point in doing a check like this

- Someone makes an API request from app XXX, to create a project
- We take that value, XXX,  from header or input  at line 228 or 230 and checks it with the same value we take from header or input at line 236.

I would say not include this decorator for that POST project API router function. But If you want to use it and follow consistency, it good. You can do it if you see value in it

2023-08-18 06:42 UTC, shimilgithub commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
ok. will make changes

2023-08-18 06:42 UTC, shimilgithub commented on app/crud/projects_crud.py
> +                compatible_with = request.headers['app']
ok. will make changes

2023-08-21 07:20 UTC, kavitharaju approved these changes

2023-08-21 07:20 UTC, merged