Lookup endpoint change
Bridgeconn/vachan-api pull request #678
Opened 2023-08-22 08:28 UTC by Joel-Joseph-George

#676

2023-08-22 08:51 UTC, shimilgithub commented on app/crud/projects_crud.py
> -def create_translation_project(db_:Session, project, user_id=None,app=None):
why reverting these changes?

2023-08-22 08:53 UTC, Joel-Joseph-George commented on app/crud/projects_crud.py
> -def create_translation_project(db_:Session, project, user_id=None,app=None):
i think happened when i merged the backup which reverted it back.

can you let me know which all files were changes reverted

2023-08-22 08:53 UTC, shimilgithub requested changes
All the changed related to `app_compatibility_check` is reverted back in this pr.  It has to be there.

2023-08-22 08:53 UTC, shimilgithub commented on app/crud/projects_crud.py
> -        project.compatibleWith = [app]
it should be there

2023-08-22 08:53 UTC, shimilgithub commented on app/crud/projects_crud.py
> -
these changes should not be reverted

2023-08-22 08:57 UTC, shimilgithub commented on app/crud/projects_crud.py
> -def create_translation_project(db_:Session, project, user_id=None,app=None):
you can refer this pr https://github.com/Bridgeconn/vachan-api/pull/665

2023-08-22 11:43 UTC, shimilgithub requested changes
Still some updates are reverted back in dockerFile and docker-compose file

2023-08-22 11:43 UTC, shimilgithub commented on app/routers/translation_apis.py
> +    print("sentencelist", sentence_list)
print statements can be removed

2023-08-22 11:43 UTC, shimilgithub commented on app/test/test_bible_books.py
> +    print("####", response.json())
remove this

2023-08-22 11:43 UTC, shimilgithub commented on docker/Dockerfile
> +FROM python:3.10
it should not be reverted

2023-08-22 11:43 UTC, shimilgithub commented on docker/docker-compose.yml
> +    image: postgres:12.7
we are using postgres 15.3 now. dont revert changes

2023-08-23 04:35 UTC, shimilgithub requested changes
Some minor codebase cleaning(only in the changes included in this pr) has to be done. Please ensure future PRs adhere to best practices as discussed in the review.

2023-08-23 04:35 UTC, shimilgithub commented on app/test/test_stop_words_generation.py
> +UNIT_URL = '/v2/nlp/stopwords'  #lookup one
When leaving comments, make it more clear so everyone can understand.

2023-08-23 04:35 UTC, shimilgithub commented on app/auth/authentication.py
> +    #     path_params is not None and "language_Code" in path_params)
Eliminate any unused code that's been commented out by you to maintain a clean codebase.

2023-08-23 04:35 UTC, shimilgithub commented on app/routers/translation_apis.py
> +                         project_id:int=Query(...,example="1022004"),
keep proper alignment.Line 71 and 72 are also the part(parameters) of `update_project` function

2023-08-23 04:35 UTC, shimilgithub commented on app/test/test_stop_words_generation.py
> +    print("###gen", response.json())
still there are few print statements added in this pr, which are not required and may increase running time. those has to be removed.

2023-08-23 05:38 UTC, shimilgithub approved these changes

2023-08-23 05:39 UTC, merged