Write apis migration
Bridgeconn/vachan-api pull request #75
Opened 2020-09-17 10:06 UTC by RevantCI

Write APIs 1-5 for the migration as per this [document](https://bridgeconn.sharepoint.com/sites/DevTeam-AgMT-VachanAPI/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={B557C75A-BCF9-49A6-BC73-B0FC517DD2AF}) in teams
That is Commentary, Dictionary, Infographics, Audio , Videos

Fixed 2 small issues also
-get all bibles api audio bibles showing even if status false - /v1/bibles
-get commentary chapter api throwing error if no book introduction - /v1/commentaries/<sourceId>/<bookCode>/<chapterId>

Closes #65

2020-09-18 03:52 UTC, kavitharaju reviewed
- It would be good to use SQL query builder for building all the SQL statements for better security.
- I have only done code review. Shall do API testing on local system and update here

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +	return -1 if not rst else rst[0]
returning `None`, when language is not present would be more intutive that `-1`, I think.

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +			execute_values(cursor,sql.SQL('insert into {} (book_id, chapter, verse, commentary) values %s').format(sql.Identifier(tableName)),
use this sql.SQL() method to create all SQL statements for better data security

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +		cursor.execute("select s.metadata->'Copyright' from sources s inner join versions v \
if you have the `sourceId` and if the only data you want is from the metadata column of the `sources` table, then why do you need the `JOIN` with versions table?

Also, the check for `content_id` can be avoided, as `source_id` is the Primary key and that identifies the exact row.

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +		tableName = "%s_%s_%s_commentary" %(language.lower(), abbreviation.lower(), str(revision).replace('.', '_'))
its good to check for the presence of(or replace) space in any of the components of tablename as that will cause issue in DB.

For example, the user could enter "K J V" for abbreviation. 
Same issue was reported in source creation for Bible.

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +		tableName = "%s_%s_%s_dictionary" %(language.lower(), abbreviation.lower(), str(revision).replace('.', '_'))
its good to check for the presence of(or replace) space in any of the components of tablename as that will cause issue in DB.

For example, the user could enter "K J V" for abbreviation. 
Same issue was reported in source creation for Bible.

2020-09-18 03:52 UTC, kavitharaju commented on agmt/main.py
> +		cursor.execute("select table_name,s.metadata from sources s inner join versions v on \
I believe the `JOIN` with `versions` table can be avoided here

2020-09-18 04:18 UTC, kavitharaju commented
I see that you have used user authentication. It checks if the user is valid. But does not check the role of the user, like if it is `Super Admin` or not. Hence any of the registered user in the AgMT App would be able to access these write APIs. Was this done intentionally?

2020-09-18 05:36 UTC, kavitharaju commented
For the write API `localhost:8000/v1/sources/infographic`, after adding the first set of data, when I try to add a second set with new revision number I get error message `"Infographics already exists"`. From the code, I understand only onle set of infographics is expected for one language. Hope this is expected behaviour. Just pointing out to confirm

2020-09-18 05:45 UTC, kavitharaju commented on agmt/main.py
> +		cursor.execute("select table_name from sources where source_id=%s", (sourceId,))
you could add a check for `content_type` of source, to confirm it is `bible` as audios are supposed to be attached only with bible's sources

2020-09-18 11:18 UTC, RevantCI commented
> * It would be good to use SQL query builder for building all the SQL statements for better security.
> * I have only done code review. Shall do API testing on local system and update here

Hi Kavitha, for simple insert queries where the table or column name is not dynamic sql builder is not required as it does nothing without the format used to add the table or column name
https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries
For simple insert the documentation recommends to use it as it is only in the last example they reccoment to use sql builders with dynamic tablename and columns
sql injection is prevented in simple queries directly 
See 4th example on the page - https://www.psycopg.org/docs/usage.html

If you have a simple way of testing it you can test it out. 
I found postman easy  to use. 
You can get the token using the login and put it in the header as Authorization: 'Bearer <token>', needs to be updated as the tokens will expire after some time.
Will just attach the postman api collection to the original issue, you can import them if you want

2020-09-18 11:34 UTC, RevantCI commented on agmt/main.py
> +		cursor.execute("select s.metadata->'Copyright' from sources s inner join versions v \
Removed the extra join, am using content_id to make sure they are trying to access a source of type commentary only using this api, will move the associated error message next to this query

2020-09-18 11:39 UTC, kavitharaju commented
@RevantCI 
> Hi Kavitha, for simple insert queries where the table or column name is not dynamic sql builder is not required as it does nothing without the format used to add the table or column name

Alright then. Need not change them

> If you have a simple way of testing it you can test it out.
> I found postman easy to use.

I tested the APIs locally using postman and added my review after that as comments above.

2020-09-18 11:49 UTC, RevantCI commented on agmt/main.py
> +		cursor.execute("select table_name from sources where source_id=%s", (sourceId,))
Have added a similar check for get commentary chapter

2020-09-18 12:04 UTC, RevantCI commented
> I see that you have used user authentication. It checks if the user is valid. But does not check the role of the user, like if it is `Super Admin` or not. Hence any of the registered user in the AgMT App would be able to access these write APIs. Was this done intentionally?

No had not done it intentially, had just taken the logic from uploadSource and put the same logic here.
Had not added the same in the documentation as well, as I wasnt aware of it.
Do you suggest we add a role check here, which one would you suggest we use for these write APIs? 
We will need to give a user login with that role for the tool we use to do the migration.

2020-09-18 12:08 UTC, RevantCI commented
> For the write API `localhost:8000/v1/sources/infographic`, after adding the first set of data, when I try to add a second set with new revision number I get error message `"Infographics already exists"`. From the code, I understand only onle set of infographics is expected for one language. Hope this is expected behaviour. Just pointing out to confirm

That was my thought, the alternative can be we can give append the rows if the table already exists
Which one do you suggest?

2020-09-21 03:45 UTC, kavitharaju commented
@RevantCI 
> Do you suggest we add a role check here, which one would you suggest we use for these write APIs?

I feel that adding auth without a rolecheck will not be very effective as the current check permits all users of AgMT. If you are checking for the role of the user, then I believe it should be the role `SUPER ADMIN`.  The other two roles we have at present, `AgMT Admin` and `AgMT Translator`,  are users who register via the AgMT App and hence should not be permitted write access to any content other than that specific to their organisations and projects. These contents are certainly not belonging to any particular user/org/project, but common to the whole Vachan. Hence, my suggestion `SUPER ADMIN`

2020-09-21 05:51 UTC, samuelanthrayose requested changes
Did a basic code review. Looks good ! Only change I'd suggest is to have the Super Admin role check for the Write API's, as @kavitharaju has already suggested

2020-09-21 06:03 UTC, samuelanthrayose commented
@kavitharaju 
 
> On infographics API...
> 
> I am not suggesting that you change it. If the present behaviour is in line with the data we have now(or may get in future), then the current logic, of **being able to create only one infographic table for a language and being able to write to it only once**, is fine. In case we get more data, later, we may not be able to add it to DB via the current APIs and DB constraints. So it is your call, to keep it as it is or change. I just want to make sure this is the expected behaviour.

Yes, as per the present data and in the near future also, we might have only one set of infographics for a language. So the current behaviour should be fine.

2020-09-21 10:47 UTC, RevantCI commented
Hi Kavitha,
Have added a role check

2020-09-21 11:10 UTC, kavitharaju approved these changes

2020-09-22 04:20 UTC, samuelanthrayose approved these changes

2020-09-22 05:39 UTC, merged