Addition of DataUpload Script
Bridgeconn/vachan-api pull request #769
Opened 2024-02-12 11:02 UTC by Joel-Joseph-George

#724

2024-02-12 13:33 UTC, shimilgithub requested changes

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/requirements.txt
> +pytz==2023.3
does all the packages are used here. especially such as jsonpickle?

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +    # postgres_schema = os.environ.get("VACHAN_POSTGRES_SCHEMA", "DataUpload")
change `DataUpload` to ` "<schema_name>"`

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +        #Token is now disabled since cms is not integrated with auth. When it is , the token need to be enabled with headers
remove first sentence

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +    # print(parsed_data)
remove if not required

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +# def add_parascriptual(csv_file_path):   #Only use if you want to add new parascriptual data using folder "parascriptuals"
enable this  function. Just mention initially like this  to enable function if required. But functions should not be commented.

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +                #     print(f"Failed to upload data for {resource_name}: {str(e)}")
remove if not required. Else uncomment it

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/upload.py
> +    file_paths = [
add a comment that these are the data files

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/fetching.py
> +import os
give a docstring  to mention what is there in this file

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/fetching.py
> +import os
find a better name for this file.

2024-02-12 13:33 UTC, shimilgithub commented on Dataupload/readme.MD
> +# DataUpload
put a space. "Data Upload"

2024-02-13 03:57 UTC, Joel-Joseph-George commented on Dataupload/requirements.txt
> +pytz==2023.3
sorry bout that, i kept the previous requirement file as it is.. i will send the updated one soon

2024-02-13 06:39 UTC, shimilgithub approved these changes

2024-02-13 06:40 UTC, merged