Changes in  dataupload script
Bridgeconn/vachan-api pull request #803
Opened 2024-04-15 03:45 UTC by AthulyaMS

- #724 

Changes:
- Uploading all audiobible resources in a single run .
- Solved the active field issue of audiobible
- Added signbible csv (ISL.csv) and its uploading script
- All resource can be uploaded in a single run except bible 
- Bible can be uploaded like each bible at a time

2024-04-15 04:24 UTC, Joel-Joseph-George commented on Dataupload/upload.py
> +    #To add  bibles seperately
i m not sure if you wanna keep both of them.. either you can add bibles to add seperately or alltogether..Ask an opinion and keep it.

2024-04-15 04:26 UTC, Joel-Joseph-George commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
is why is this commented?

2024-04-15 04:54 UTC, AthulyaMS commented on Dataupload/upload.py
> +    #To add  bibles seperately
Maybe the commented one ,we have to use in future

2024-04-15 04:54 UTC, AthulyaMS commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
For parascriptural we have seperate uploading script for bible video and infographics .Here this is the code for adding a new parascriptural data ,so it is commented

2024-04-15 04:57 UTC, Joel-Joseph-George commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
i think thats not the right way for this.. if you are not using this you can remove it . Else mention why it is commented it out

2024-04-15 04:58 UTC, Joel-Joseph-George approved these changes, later dismissed

2024-04-16 02:26 UTC, shimilgithub requested changes

2024-04-16 02:26 UTC, shimilgithub commented on Dataupload/upload.py
> +TOKEN = "VaChAn#CMS#1903"
keep placeholder instead of passing token.

Use `<valid_token>` or similar in place of token

2024-04-16 02:26 UTC, shimilgithub commented on Dataupload/upload.py
> +# def add_resources_v2():
why this is commented?

2024-04-16 02:26 UTC, shimilgithub commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
remove if this line is not used

2024-04-16 07:39 UTC, AthulyaMS commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
This parascriptutal code we are not using .We have seperate function for uploading infographics and biblevideo. I can comment the whole function in next pr

2024-04-16 07:39 UTC, AthulyaMS commented on Dataupload/upload.py
> +# def add_resources_v2():
We're not using this function in the data upload process. It was already there, but since it's not being utilized, I've commented it out.

2024-04-16 07:39 UTC, AthulyaMS commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
This parascriptutal code we are not using .We have seperate function for uploading infographics and biblevideo. I can comment the whole function in next pr

2024-04-16 09:58 UTC, shimilgithub commented on Dataupload/upload.py
> +# def add_resources_v2():
if its needed you can remove. but do a check once again

2024-04-16 09:59 UTC, shimilgithub commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
good to remove unused /commented code from this pr

2024-04-16 11:21 UTC, AthulyaMS commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
@shimilgithub  updated

2024-04-16 11:21 UTC, AthulyaMS commented on Dataupload/upload.py
> +# upload_data(data, parascript_url)
@shimilgithub  updated

2024-04-16 11:43 UTC, shimilgithub approved these changes

2024-04-16 11:43 UTC, merged