Landing Page updations
Bridgeconn/vachan-api pull request #809
Opened 2024-04-24 06:52 UTC by Joel-Joseph-George

#808

2024-04-24 07:49 UTC, AthulyaMS submitted a review, later dismissed

2024-04-29 05:18 UTC, shimilgithub commented on app/static/data/services.json
> +                "link":"https://stagingapi.vachanengine.org/v2/auth/docs",
Need to map to respective links instead of directly pointing to staging. eg : In staging it should navigate to respective staging APIs and in production , it should navigate to APIs in production. You can refer  `API Documentation` link in `Getting Started` tab.

2024-04-29 05:19 UTC, shimilgithub requested changes
rest look fine except this change

2024-04-29 06:39 UTC, shimilgithub approved these changes

2024-04-29 06:39 UTC, merged