Feature: tests for content types
Bridgeconn/vachan-api pull request #85
Opened 2020-10-21 07:56 UTC by kavitharaju

* contains the changes in the PR [V2 API Planning](https://github.com/Bridgeconn/vachan-api/pull/78)
* Test settings for Database connection
* Unit tests for the /v2/contents GET and POST APIs

2020-10-28 06:15 UTC, kavitharaju commented
As we decided to use SQL alchemy for test DB, we need to change the setups in app/tests/__init__.py.
@RevantCI  expecting your help for that

2020-11-09 07:23 UTC, RevantCI requested changes
Hi Kavitha can you go throught the comments for changes that I have suggested and do the changes if you agree.

2020-11-09 07:50 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert isInstance( response1.json(), list)
changed

2020-11-09 07:51 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	response = client.get()
changed

2020-11-09 07:51 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert isInstance( response.json(), list)
changed

2020-11-09 07:54 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert response.json()['error'] == "Input validation Error"
Changed

2020-11-09 07:54 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert len(response.json()) < 3
Changed

2020-11-09 07:55 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert response.status_code == 200
changed

2020-11-09 07:55 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert response.json()['message'] == "Content type %s created successfully."%data
Yes. We can do that. Changed.

2020-11-09 07:57 UTC, kavitharaju commented on app/test/test_contentTypes.py
> +	assert response.json()["data"]["contentType"] == data
changed

2020-11-11 11:33 UTC, RevantCI approved these changes

2020-11-20 04:38 UTC, merged